### ISSUE TITLE
Remove "name" field from the edit view

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockwise/lockwise-android#1010]
Instead of displaying the "name" field on the edit entry view, let's remove that field entirely. We can reintroduce it when we're able to actually edit (and create) titles for credentials.

Currently the edit view displays the web address in the name field, which is a duplicate of the "web address" field below it.

**Comment by eliserichards** [comment]
<img width="366" alt="image" src="https://user-images.githubusercontent.com/43795363/67434796-b82be380-f59f-11e9-852a-043b159f4a8b.png">

<img width="368" alt="image" src="https://user-images.githubusercontent.com/43795363/67434827-c548d280-f59f-11e9-918f-725c1b71f5ef.png">

**Comment by abodea** [comment]
Re-opening this, as I can still see the `Name` field in Login Edit view. 
Using **`3.1.0 (Build 5362)`** with **Google Pixel 3a XL(Android 10).**
![ezgif-1-5a38b10100fa](https://user-images.githubusercontent.com/42831109/68120298-a2a6aa00-ff0d-11e9-9b1c-1ec2e1b9d429.gif)

**Comment by cadeyrn** [comment]
I can also still see the name field in the edit view (3.1.0 Build 5362, Android 10).

**Comment by abodea** [comment]
Verified as fixed using the latest master build **`3.1.0(5452).`**
Based on my comment I will close this issue.
@cadeyrn thank you for checking, this will be in the next RC.

**Comment by abodea** [comment]
Note that I verified this issue on **`3.2.0 (Build 5522)`** too with **`Google Pixel 3a XL(Android 10).`**
