### ISSUE TITLE
Edit Login Section-Wide white text area around context menu: cut, copy and paste

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-lockwise/lockwise-android#1014]
## Steps to reproduce
1. Open Lockwise application.
2. Log with an existing firefox account that contains login entries.
3. From "All Logins" module tap on a login entry.
4. From top right corner tap on the 3 dots.
5. Tap on the "Edit" option.
6. Long tap on the "Username" field.
### Expected behavior
The Menu with options: Cut, Copy, Paste etc is displayed.
### Actual behavior
Besides the menu with the mentioned options, a wide white text area is displayed.
### Device & build information
* Device: Samsung Galaxy S8+ (Android 8.0.0)
* Build version:  Release 3.0.0 RC2 (Build 5177)
### Notes
The same outcome is present for "Password" field.
After a couple of attempts to long tap on any of the fields and having the application in background in this state and afterwards long tap on any of the fields, a crash will be present.
Firefox Lockwise has stopped. Close app.
Attachments: 
[Video](https://drive.google.com/open?id=1IOENK-eSsuFwFWgAVZDHAl7htiES0Qqw)

**Comment by eliserichards** [comment]
Fixed in #1036
