### ISSUE TITLE
Search bar text handles have violet background

### ISSUE THREAD

**Issue by lucacataldo** [mozilla-lockwise/lockwise-android#1035]
## Steps to reproduce

1. Login
2. Tap search icon on top right
3. Make text handle appear by tapping and holding in search field

### Expected behavior

Text handle drawable shows up with appropriate accent color and transparent background

### Actual behavior

Text handle drawable shows up with default android holo color and a background matching it's parent

### Device & build information
* Device: Present on Galaxy S8 & Nexus 5X android emulator
* Build version: ?
### Notes
Attachments: 
![image](https://user-images.githubusercontent.com/35984346/67911491-1dae4000-fb5d-11e9-9fc9-0fc7e416edf0.png)

**Comment by lucacataldo** [comment]
I'd like to work on this

**Comment by abodea** [comment]
Hi @lucacataldo I believe this issue is related with #298 since then the app changed but still they look similar.

**Comment by lucacataldo** [comment]
Yup, looks like it is, I referenced it in my PR  ( #1036 ) appears to be stemming from the main theme (and other parent themes) setting a background which is them applied to ALL child elements including handles and popup menus that would otherwise be transparent.

**Comment by abodea** [comment]
Verified as fixed on **`3.2.0 (Build 5522)`** with **`Google Pixel 3a XL(Android 10).`**
