### ISSUE TITLE
Whooops! Wrong URL displayed when accessing Learn More from Lockwise settings

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#1048]
## Steps to reproduce
1. Launch Lockwise.
2. Login with valid credentials.
3. Access settings and tap on Learn More.
### Expected behavior
The correct article for the `Support` page is displayed when tapping on the `Learn More`.
### Actual behavior
Whooops! Wrong URL displayed when accessing Learn More from Lockwise settings.
### Device & build information
* Device: **Google Pixel 3a XL(Android 10)**
* Build version: **3.1.0 (Build 5361)**
### Notes
Attachments: 
![xd1](https://user-images.githubusercontent.com/42831109/68115100-45f0c280-ff00-11e9-9ba3-b93bec949863.gif)

**Comment by eliserichards** [comment]
New URL: https://support.mozilla.org/en-US/kb/firefox-lockwise-and-privacy

**Comment by abodea** [comment]
Verified as fixed on **`3.2.0 (Build 5522)`** with **`Google Pixel 3a XL(Android 10).`**
