### ISSUE TITLE
Close keyboard when exiting feedback form

### ISSUE THREAD

**Issue by eliserichards** [mozilla-lockwise/lockwise-android#1057]
## Steps to reproduce
1. Log in to Lockwise
2. Open menu, go to **Provide Feedback**
3. Enter text in text box
4. Exit feedback

### Expected behavior
Keyboard closes

### Actual behavior
Keyboard doesn't close, has to be manually closed

<img width="300" alt="image" src="https://user-images.githubusercontent.com/43795363/68429038-f6fe9380-0172-11ea-8ed0-af6ebd8c3a3c.png">  <img width="300" alt="image" src="https://user-images.githubusercontent.com/43795363/68429063-01b92880-0173-11ea-8ecb-8d35b3ff283a.png">

### Device & build information
* Device: Pixel 2
* Build version: 3.1.0

**Comment by abodea** [comment]
Verified as fixed on **`3.2.0 (Build 5522)`** with **`Google Pixel 3a XL(Android 10).`**
Note that the keyboard is closed every time when exiting the feedback form.
