### ISSUE TITLE
Cleanup add/update new login data

### ISSUE THREAD

**Issue by jhugman** [mozilla-lockwise/lockwise-android#1064]
There are a number of data integrity issues with the current add/edit logins; with potential inconsistencies between add/edit and autofill/capture

This issue captures the need to fix these problems and unify how new logins are added and existing ones are edited; this will most likely need to go in the `ItemDetailStore` or `DataStore`.

 * ensure the `formSubmitURL` makes sense, including adding the scheme.
 * password changed dates.
 * recently used from autofill.
 * update list after insert.

**Comment by abodea** [comment]
Verified as fixed on the latest version `3.3.0 (Build 5784)` using **Google Pixel 3a XL(Android 10), Samsung Galaxy S10+(Android 9), Samsung Galaxy S8+(Android 8), Samsung Galaxy S7(Android 7).**
Note that everything worked as expected, I added + updated new accounts and when I tried to autofill, the correct data was imported. Also, I did a smoke test.

I couldn't find any regressions.
Based on my comment I will close this issue.
