### ISSUE TITLE
Search Firefox Lockwise bottom button color from autofill screen is dark

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#1072]
## Steps to reproduce
1. Launch Lockwise and login with valid credentials.
2. Access any account.
3. Tap on the web address in order to reach the desired website.
4. Tap on the username field.
5. From the autofill screen scroll until the bottom where `Search Firefox Lockwise` button is displayed.
### Expected behavior
The `Search Firefox Lockwise` button is the same color as the rest of the pop-up screen.
### Actual behavior
Search Firefox Lockwise bottom button from autofill screen color is dark
### Device & build information
* Device: **`Google Pixel 3a XL(Android 10).`**
* Build version: **`3.2.0 (Build 5522).`**
### Notes
![Screenshot_20191119-111741](https://user-images.githubusercontent.com/42831109/69133855-3c01be80-0abf-11ea-82f9-1b84aa07eb53.png)

**Comment by changecourse** [comment]
Elevating this issue priority, as the button is now unreadable and no longer adherent to color contract accessibility guidelines.

**Comment by eliserichards** [comment]
I'm wondering if this is a regression from the style/theme changes in #1061

**Comment by eliserichards** [comment]
I can't seem to repro this on my Pixel 2 or Pixel 3. @abodea is this only happening on this one website?

<img width="377" alt="image" src="https://user-images.githubusercontent.com/43795363/69181526-df110300-0ad4-11ea-9b1b-62d81f5247e9.png"> 
<img width="387" alt="image" src="https://user-images.githubusercontent.com/43795363/69181931-a9b8e500-0ad5-11ea-808f-2c50f67f4a14.png">

**Comment by abodea** [comment]
Hello @eliserichards, I can reproduce this issue on any site using **`Google Pixel 3a XL(Android 10). `**

**Comment by changecourse** [comment]
@eliserichards we were able to reproduce this issue on Firefox Preview, with the device theme set to dark mode. I'm not positive that this is the same as what @abodea found, but it's certainly reproduceable there. 

![Screenshot_20191126-121201](https://user-images.githubusercontent.com/6164801/70272002-bfc8d580-1764-11ea-854c-9b801bb7555d.png)

We may need to set a style override if the device theme or browser theme (Fenix) is set to dark mode

**Comment by abodea** [comment]
@changecourse I can confirm that it is the same issue.
In my example, I had a lot of accounts for autofill, but the bottom `Search Firefox Lockwsie` is the same dark.
Also, I tried the following:

|Device | Device Theme| Fenix Theme | Reproducible? | 
|------------- | :-------------: |:-------------:|:-------------: |
| Google Pixel 3a XL(Android 10) | Light | Light | ❌ | 
| Google Pixel 3a XL(Android 10) | Light | Follow device theme | ❌ | 
| Google Pixel 3a XL(Android 10) | Light | Dark | ❌ | 
| Google Pixel 3a XL(Android 10) | Dark | Light | ✅ | 
| Google Pixel 3a XL(Android 10) | Dark | Follow device theme | ✅ | 
| Google Pixel 3a XL(Android 10) | Dark | Dark | ✅ | 
| Samsung Galaxy S10+(Android 9) | Light | Light | ❌ | 
| Samsung Galaxy S10+(Android 9) | Light | Follow device theme | ❌ | 
| Samsung Galaxy S10+(Android 9) | Light | Dark | ❌ | 
| Samsung Galaxy S10+(Android 9) | Dark | Light | ✅ | 
| Samsung Galaxy S10+(Android 9) | Dark | Follow device theme | ✅ | 
| Samsung Galaxy S10+(Android 9) | Dark | Dark | ✅ | 

I do believe this issue only occurs for the Android 10 using the device dark theme.

**Comment by ddurst** [comment]
Just noting to ensure that #454 is also fixed by this.

**Comment by abodea** [comment]
Verified as fixed on **v.4.0.0(6016)** using **Google Pixel 3 XL(Android 9), Samsung Galaxy S10+(Android 9).**
@eliserichards everything looks good now :tada: the search button is displayed correctly.
