### ISSUE TITLE
Update to app services 0.44.0

### ISSUE THREAD

**Issue by eliserichards** [mozilla-lockwise/lockwise-android#1084]
### Vision statement / What / Requirements
Update to the latest version of app services: https://github.com/mozilla/application-services/releases/tag/v0.44.0

### Impact
Newest version includes dupe checking behind the scenes for add and update.

### Acceptance criteria
- [ ] Update AS 0.44.0
- [ ] Handle new exceptions being thrown on `.add` and `.update` (see the [PR](https://github.com/mozilla/application-services/pull/2101))

**Comment by jhugman** [comment]
We can go to v0.46.0 before we need to do the work to fix #1103.
