### ISSUE TITLE
Can't log in on a landscape-only device

### ISSUE THREAD

**Issue by JJJollyjim** [mozilla-lockwise/lockwise-android#1101]
## Steps to reproduce

Open the app on a device or emulator that runs in landscape mode

### Expected behavior

I can log in to the app, then hopefully access passwords somehow

### Actual behavior

The login button is off-screen and cannot be scrolled to (or accessed via keyboard, as far as I can tell)

### Device & build information
* Device: Planet Gemini (WiFi)
* Build version: Google Play 3.2.0

### Attachments

![photo_2019-11-30_22-05-08](https://user-images.githubusercontent.com/691552/69898344-3eb4bb80-13bd-11ea-8c68-bece2d1a2fb0.jpg)

**Comment by lucacataldo** [comment]
Hey, I'm going to have a look and see if I can get to the bottom of this.

**Comment by eliserichards** [comment]
Hi @JJJollyjim! We don't currently support landscape on Lockwise Android, only portrait mode. Thanks for your report!
