### ISSUE TITLE
Allow saving multiple passwords for a username on a site/app

### ISSUE THREAD

**Issue by santiagofn** [mozilla-lockwise/lockwise-android#1125]
There are cases where a site/app needs more than a password for a user to login (they have more than one password field). Ex. bank Santander (Argentina):

https://www2.personas.santander.com.ar/obp-webapp/angular/#!/login
![image](https://user-images.githubusercontent.com/8375708/71770463-73131e80-2f0b-11ea-93b0-90202239062e.png)

Lockwise seems to have a one-to-one relationship between a username on a site/app and its saved password. You cannot save 2 different passwords for the same username:

![image](https://user-images.githubusercontent.com/8375708/71770633-963ecd80-2f0d-11ea-82e7-7a85a6dfcc24.png)

This means that these cases can't be handle correctly. The only available option would be to use the same pw in different fields, which is wrong:

![image](https://user-images.githubusercontent.com/8375708/71770565-e10c1580-2f0c-11ea-9281-de98effbd9fe.png)
![image](https://user-images.githubusercontent.com/8375708/71770639-a3f45300-2f0d-11ea-9787-d9771af430f4.png)

It would be really helpful if a username could have more than one password saved on a site/app as it would result on a correct handling of these cases.

**Comment by eliserichards** [comment]
Closed in favor of #1043
