### ISSUE TITLE
Error while editing Username: A login with that user name already exists error is shown

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockwise/lockwise-android#1126]
## Steps to reproduce
Tap on a login to edit it
Change the Username field 
### Expected behavior
It is  possible to edit a login
### Actual behavior
No matter the  new username you select, the error is shown: `A login with that username already exists`
### Device & build information
* Device: Pixel 2
* Build version: master 0dfe1a1
### Notes
Attachments: 
<img width="100" alt="Screenshot 2020-01-07 at 12 42 55" src="https://user-images.githubusercontent.com/1897507/71893480-1783a380-314c-11ea-8cb4-66b603d6ae91.png">

@eliserichards this might be a regression after the manual create feature landed, since this was working fine before that.

**Comment by abodea** [comment]
Verified as fixed on **v.4.0.0(6016)** using **Google Pixel 3 XL(Android 9), Samsung Galaxy S10+(Android 9).**
Note that now the error is displayed only for the accounts with the same username.
