### ISSUE TITLE
Discard changes actually keeps the changes done if Save button has been pressed before

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockwise/lockwise-android#1127]
## Steps to reproduce
Open a login to edit it
Change the username value
Tap on Save button
Tap on Close button
Tap on Discard changes and Discard in the confirm dialog
### Expected behavior
Changes are not applied
### Actual behavior
Even though Discard option is selected, changes in username are not discarded

### Device & build information
* Device: Pixel 2
* Build version: master 0dfe1a1
### Notes
Attachments: Please see video: https://youtu.be/QkN9XqJVDro

**Comment by abodea** [comment]
Verified as fixed on **v.4.0.0(6016)** using **Google Pixel 3 XL(Android 9), Samsung Galaxy S10+(Android 9).**
Note that now when I tried to save an account with the same username I didn't get the error that an account already exists with that username.
I was able to correctly edit and save the login.
