### ISSUE TITLE
Please add the ability to point to custom syncserver.

### ISSUE THREAD

**Issue by tublitzed** [mozilla-lockwise/lockwise-android#1129]
### Why/User Benefit/User Problem

It'd be ideal not to have to do a custom Lockwise build to test Sync changes against staging. If there were a flag/config pref/toggle somewhere that would let us either:

a) Point to staging only
OR
b) Set our own sync host (which would allow pointing to staging and [might be more flexible for self-hosters?](https://github.com/mozilla-lockwise/lockwise-android/issues/542)).

then we could make changes to Sync with more confidence that we can test them against staging before rolling to prod.

### Acceptance Criteria (how do I know when I’m done?)

* We're able to point Lockwise to staging based Sync server in Fenix.

### Not included

* Fennec - I don't think it's needed right now since Fenix is close; probably not worth the effort.

**Comment by eliserichards** [comment]
Related to #542

**Comment by ddurst** [comment]
Related to https://github.com/mozilla-lockwise/lockwise-ios/issues/1175

**Comment by eoger** [comment]
Is this the same as https://github.com/mozilla-lockwise/lockwise-android/issues/542? Should we close one of the two? Just so you know I'm working on this on the a-s side.

**Comment by tublitzed** [comment]
@eoger ah, yup. I'll close this out as a dupe and we can track via #542
