### ISSUE TITLE
Improve requirements for Create hostnames

### ISSUE THREAD

**Issue by eliserichards** [mozilla-lockwise/lockwise-android#1131]
### Expected behavior
A hostname should be a valid address, not just "http://" or "www." (or an IP address)

### Actual behavior
Our string matching allows a non-valid hostname (see screenshot) because we only check the following: 
- Contains "http://" or "https://"
- Contains "www."
- Not empty

<img width="325" alt="image" src="https://user-images.githubusercontent.com/43795363/71937063-d94cab00-3170-11ea-8e11-74b540e72315.png">

Possible new error message: "Please enter a valid hostname"? @changecourse

**Comment by turkergoksu** [comment]
I would like to work on this. Do I need to create a new branch for this issue?

**Comment by eliserichards** [comment]
Fixed by #1140
