### ISSUE TITLE
The password is not auto-hidden when creating a new entry

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#1135]
## Steps to reproduce
1. Launch lockwise.
2. Login with valid credentials.
3. On the entries, section tap on the `+` button in order to create a new entry.
4. Add the password for the account.
### Expected behavior
The password should be hidden while typing until the user wants to reveal it.
### Actual behavior
The password is not hidden when creating a new entry.
### Device & build information
* Device: **Google Pixel 3a XL(Android 10).**
* Build version: **Latest master version 3.3.0 from 1/13.**
### Notes
Attachments: 
![ezgif-2-d5d5e2f8dfaf](https://user-images.githubusercontent.com/42831109/72264253-18707580-3623-11ea-913a-697c88e16d0e.gif)

**Comment by eliserichards** [comment]
Closing - this is expected behavior 😄
