### ISSUE TITLE
Username field does not work properly when removing all characters, a new one is always introduced

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockwise/lockwise-android#1141]
## Steps to reproduce
Open an entry and tap on Edit
Remove completely the username
Tap on Save

### Expected behavior
The username is correctly removed

### Actual behavior
Upon tapping on Save once the username has been removed, a new character, the last one removed, is automatically inserted

### Device & build information
* Device: Pixel 3
* Build version: master 69d8b36
### Notes
Attachments: Please see video attached
https://youtu.be/ebKi5D2WPnQ

**Comment by isabelrios** [comment]
@eliserichards just checked while creating and this can be reproduced...The steps would be:
-Enter web address, username and password
-Remove username before tapping on Save button
-Then tap on Save

Actual
The username appears with the last character typed before removing it completely.

Hope this helps, thanks!

**Comment by abodea** [comment]
Verified as fixed on **v.4.0.0(6016)** using **Google Pixel 3 XL(Android 9), Samsung Galaxy S10+(Android 9).**
Note that on both edit and create sections, the login is saved correctly.
