### ISSUE TITLE
The "Hostname/Password cannot be empty" error is displayed even if there is no attempt to save a login

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#1158]
## Steps to reproduce
1. Launch Lockwise.
2. Login with valid credentials.
3. Tap on the `+`.
4. Tap on the `Web address` or `Password fields` but don't insert any data.
### Expected behavior
The "Hostname/Password cannot be empty" error should not be displayed until there is an attempt to save a login without one of these filled.
### Actual behavior
The "Hostname/Password cannot be empty" error is displayed even if there is no attempt to save a login
### Device & build information
* Device: **Samsung Galaxy S10+(Android 9)**
* Build version: **4.0.0(6016)**
### Notes
Attachments: 
![Screenshot_20200130-161240 (1)](https://user-images.githubusercontent.com/42831109/73459512-a8caec00-437f-11ea-8664-f785cd03018f.png)

**Comment by eliserichards** [comment]
This is expected behavior 👍
