### ISSUE TITLE
Choose dialog button colors when view is constructed

### ISSUE THREAD

**Issue by eliserichards** [mozilla-lockwise/lockwise-android#1167]
### Vision statement / What / Requirements
The current implementation of the `DialogViewModel` class allows the button color of the dialog to be specified:

```
data class DialogViewModel(
    @StringRes val title: Int? = null,
    @StringRes val message: Int? = null,
    @StringRes val positiveButtonTitle: Int? = null,
    @StringRes val negativeButtonTitle: Int? = null,
    @ColorRes val positiveButtonColor: Int? = null
)
```

The view model should not be dealing with any resources (colors, dimens, etc.). The `positiveButtonColor` `@ColorRes` value should really be decided on how important the model says this button is. Then, when the view is constructed, we should be deciding the color based upon that — e.g.. "Is the button action destructive? = `R.color.red`".

### Acceptance criteria
* Remove `positiveButtonColor` from the `DialogViewModel`
* Choose the button color where the view is constructed

**Comment by JG916** [comment]
Hi, is this project open to contributions from non-mozilla developers? I can handle this issue if so. Thanks!

**Comment by eliserichards** [comment]
Hi @JG916! This project is definitely open to outside contributors! Feel free to open a pull request from your fork when you are ready for code review and we will take a look :smile:
