### ISSUE TITLE
Add animation when selecting an account in the main menu section

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#1169]
### Why/User Benefit/User Problem
As a Lockwise user, I wanna see exactly what account I'm selecting before accessing it.
### Acceptance Criteria (how do I know when I’m done?)
When selecting an account, there will be an animation.
### Notes
Similar animation like it's in settings menu can be added for the accounts.

**Comment by eliserichards** [comment]
Closing as dupe of #1172
