### ISSUE TITLE
Add the possibility to multi-select accounts on the home screen

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#1173]
### Why/User Benefit/User Problem
As a Lockwise user, I want to be able to multi-select accounts in case I wanna delete more at once. 
If categories will be implemented this will help to move the accounts easier.
### Acceptance Criteria (how do I know when I’m done?)
More accounts can be selected on the home screen.

**Comment by eliserichards** [comment]
Close as dupe of #1172
