### ISSUE TITLE
Add the legacy telemetry client id to the deletion request ping

### ISSUE THREAD

**Issue by eliserichards** [mozilla-lockwise/lockwise-android#1195]
### Vision statement / What / Requirements
Add the legacy telemetry client id to the deletion request ping to comply with data protection regulations (e.g. GDPR, CCPA) by [following the instructions for adding secondary ids to the deletion request ping.](https://mozilla.github.io/glean/book/user/pings/deletion_request.html)

This will give the user control over their tracked telemetry (linked through legacy telemetry client id) and prevent any further telemetry from being tracked for their account.

### Impact
Required by California Privacy Act deadline in June

**Comment by eliserichards** [comment]
iOS issue: https://github.com/mozilla-lockwise/lockwise-ios/issues/1212

**Comment by liuche** [comment]
How is this issue going @eliserichards ? Are you still spending time on it in this sprint or should we move it out?
