### ISSUE TITLE
'null' pop up in Google Messages after Android 11 upgrade

### ISSUE THREAD

**Issue by darkdatter** [mozilla-lockwise/lockwise-android#1228]
## Steps to reproduce

- Install Lockwise on Android
- Upgrade device to Android 11
- Launch any Google app

### Expected behavior
App should launch as normal.

### Actual behavior
App launches and a bubble containing 'null' appears on the bottom of the screen.

### Device & build information
* Pixel 4XL
* Android: RP1A.200720.009
* Lockwise v4.0.1
### Notes
See associated issue:
[https://support.google.com/pixelphone/thread/69916905?hl=en](url)

**Comment by ToadKing** [comment]
Dupe of #1224
