### ISSUE TITLE
i dont have autofill button on settings

### ISSUE THREAD

**Issue by itskarim** [mozilla-lockwise/lockwise-android#1232]
## Steps to reproduce
entering the settings of lockwise but it seems that the button is not listed
### Expected behavior
a button to enable autofill should appear in lockwise settings
### Actual behavior
when I enter the settings of lockwise I can's see the autofill button
### Device & build information
* Device: 7.0
* Build version: 4.0.1 (6349)
### Notes
Attachments:

**Comment by tomscholz** [comment]
What device are you using?

**Comment by z0xrv** [comment]
@tomscholz the problem is that android 7 not supported by lockwise

**Comment by Webbeh** [comment]
Android 7 did not support password autofilling.
Update your android version if you can, or change your device.

Not a lockwise issue.
