### ISSUE TITLE
Ship 4.0.2

### ISSUE THREAD

**Issue by st3fan** [mozilla-lockwise/lockwise-android#1239]
Issue to keep track of the work needed to ship 4.0.2

**Comment by Webbeh** [comment]
Thanks for picking this up. Let us know if you need anything.

Been using my compiled apk for two weeks without issue on android 11 (oneplus 8 pro).

**Comment by st3fan** [comment]
Just leaving a note there that the 4.0.2 release that is now published in the GitHub releases will most likely not ship to the Play Store. Unfortunately this release is built against SDK 28, which the Play Store does not accept anymore.

We are currently investigating options and will most likely ship a 4.0.3 instead.

**Comment by st3fan** [comment]
Closing this bug for now.
