### ISSUE TITLE
Ship 4.0.3

### ISSUE THREAD

**Issue by st3fan** [mozilla-lockwise/lockwise-android#1244]
We're getting closer to a 4.0.3 release that includes:

 * Fix the for "null" toast
 * Upgrade to Android SDK 29

This bug is to keep track of the status and the work to be done. Currently blocking:

 * [x] Review https://github.com/mozilla-lockwise/lockwise-android/pull/1243
 * [x] Create a signed build of #1243 for testing
 * [x] Ask QA to run a smoke test
 * [x] Land #1243 and creating a release
 * [x] Hand over APK to Release Management

Documentation for release building at https://github.com/mozilla-lockwise/lockwise-android/blob/master/docs/releases.md

cc @jonalmeida @jhugman

**Comment by st3fan** [comment]
Creating a release build is currently timing out after 90 minutes. Unclear what is going on as the 4.0.2 build took 11 minutes.

**Comment by st3fan** [comment]
Release is at https://github.com/mozilla-lockwise/lockwise-android/releases/edit/release-v4.0.3 - the plan is to ask for a quick QA sign off (as a smoke test was already done) and then ship this early in the week of December 14th 🔒🦊🎅

**Comment by mariomenjr** [comment]
Thanks for the updates! 
Is this being shipped through the Play Store soon? 😯

**Comment by st3fan** [comment]
Lockwise 4.0.3 was just pushed to 100%. Apologies for the delay.

**Comment by Webbeh** [comment]
Thank you very much!

EDIT: Just updated, confirmed working on Oneplus 8 Pro / Android 11
