### ISSUE TITLE
"null" toast notification on invalid text entry fields

### ISSUE THREAD

**Issue by KD0AZT** [mozilla-lockwise/lockwise-android#1248]
## Steps to reproduce
When Lockwise is set as the default autofill service on Android 11, tapping into a non- username / password text entry fields.
### Expected behavior
Lockwise takes no action for autofilling the text entry field
### Actual behavior
Lockwise generates a "null" toast notification
### Device & build information
* Device: Samsung SM-G986U
* Build version: 4.0.1 (6349) 
### Notes
Changing the default autofill service from Lockwise to Google or Samsung Pass prevents the "null" toast.
Attachments:
![Screenshot_20201211-153846_Messages](https://user-images.githubusercontent.com/33142442/103472859-47f22380-4d47-11eb-82ec-839976f92952.jpg)

**Comment by Webbeh** [comment]
#1219 
#1224 
#1237 
#1239 
#1244

You can already download the latest APK in the releases [here, on this github](https://github.com/mozilla-lockwise/lockwise-android/releases/tag/release-v4.0.3). That APK doesn't have the bug anymore but isn't yet on the play store.
