### ISSUE TITLE
Future App Development Information and Feature Request-

### ISSUE THREAD

**Issue by Jpersh27** [mozilla-lockwise/lockwise-android#1256]
Hello @eliserichards @jonalmeida and @st3fan or whoever else is actively Developing for the Android version of lockwise. At this point I'm unable to tell who is active in this repository because there has been No actions, No pull requests, No issues attended too or closed in almost 90 days now. 

• I have been following this repository since the Android application was released back in the year 2019 this month. In 2 days this application will have been on the Google play store for over two years.

• It is still lacking two major feature that other similar open source password managers have and that is Dark Mode Support and TOTP Authenticator support for Logins.

1.) Will Dark Mode be adopted anytime soon? (Bitwarden and numerous other Open Source password managers offer this feature)

2.) Will TOTP Authenticator Code Support for Logins be adopted anytime soon? (So users don't have to rely of Third party applications for codes. Bitwarden and numerous other Open Source password managers offer this feature)

• It is also missing the ability to create and Store Notes, Cards, Identity, Folder creation, password generator, Ability to take screenshots, etc...

3.) Who are the active Android Developers for this application? Or has this project been pushed aside? 

Thank you and have a nice rest of your day today and hope to hear from someone soon!

**Comment by Jpersh27** [comment]
So will anyone from Mozilla help me or will I continue to be ignored like the other 263 open issues that are not being attended too?? 

• I have tagged the following individuals below based upon who have had the most contributions to this repository. Will include screenshots to this comment down below.

![IMG_20210325_234853.jpg](https://user-images.githubusercontent.com/77606699/112574480-baadf080-8dc4-11eb-9c72-531732b62d13.jpg)

![IMG_20210325_234903.jpg](https://user-images.githubusercontent.com/77606699/112574503-c994a300-8dc4-11eb-8c98-b3c019ef8d1e.jpg)

@jonalmeida @st3fan @jhugman @eliserichards @devinreams @sashei @abodea

**Comment by myrust** [comment]
Switch to Bitwarden, this project is not active! No more code submissions since last year! It is no different from a dead project!
