### ISSUE TITLE
Investigate FingerprintManager to eliminate `Start` and `Stop` actions

### ISSUE THREAD

**Issue by jhugman** [mozilla-lockwise/lockwise-android#166]
The finger print sensor needs to be managed in an imperative manner. 

Currently, we have a FingerprintStore which accepts Start and Stop actions, but also has an `AuthenticationState` observable.

We should be able to replace start and stop actions with method calls during `doOnSubscribe()` and `doOnDispose()` respectively.

Followup to #158

**Comment by eliserichards** [comment]
Not needed once we switch to `BiometricPrompt` (see #153).
