### ISSUE TITLE
Rename `CommonFragment` to `Fragment`.

### ISSUE THREAD

**Issue by jhugman** [mozilla-lockwise/lockwise-android#167]
We currently have `CommonFragment`, `Presenter` and `DialogFragment`.

We should rationalize this naming scheme into something more consistent.

`mozilla.lockbox.view.DialogFragment` is a subclass of `android.support.v4.app.DialogFragment`

We should rename `CommonFragment` to a similar `mozilla.lockbox.view.Fragment`.

This is a followup from #158.

**Comment by chamini2** [comment]
I can't find CommonFragment from searching in the project, should this be closed?
