### ISSUE TITLE
Add leak detection solution to CI

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockwise/lockwise-android#172]
Follow up to #140

>There is a static analyzer that Facebook makes (leakcanary is made by Square) called [Infer](https://fbinfer.com/docs/getting-started.html) that I have no experience with, but could be useful as a CI tool

**Comment by jhugman** [comment]
This should not be shipped with the release builds.

**Comment by sashei** [comment]
Let's just rely on LeakCanary in the debug builds
