### ISSUE TITLE
Communicate to users when Sync fails

### ISSUE THREAD

**Issue by nickbrandt** [mozilla-lockwise/lockwise-android#184]
We need to communicate to users when Sync fails and the user has to return to Firefox to re-initiate the Sync.

When Lockbox can't load logins, we need a way to communicate to users that something is wrong and Lockbox can't fix it (eg the Sync service crashed). We'll want to:

1. inform users that something went wrong and
2. to recover, the user must go back to Firefox (desktop or iOS or Fennec) and manually initiate a sync.

*Requires an addition to the Lockbox site FAQ ([#74](https://github.com/mozilla-lockbox/mozilla-lockbox.github.io/issues/74)) in main Lockbox site repo

### Visual Design
**InVision**
No Entries: https://mozilla.invisionapp.com/share/3SN35UHWJDX#/329017814_Sync_Fails_-_No_Entries
Has Entries: https://mozilla.invisionapp.com/share/3SN35UHWJDX#/329017815_Sync_Fails_-_Has_Entries

**Zeplin**
No Entries: https://zpl.io/agrOPMQ
Has Entries: https://zpl.io/bz1jADA

Note: The "show me how" and "learn more" links would direct to the Lockbox FAQ site:
https://lockbox.firefox.com/faq.html#how-do-i-manually-sync-my-entries-in-firefox

**Comment by devinreams** [comment]
This was a stretch goal. Downgrading for launch.

Workarounds allow users to refresh manually but also know this is an important user feedback.

**Comment by sashei** [comment]
Let's close this in favor of #186.
