### ISSUE TITLE
Accessibility Scanner: touch target size  findings

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockwise/lockwise-android#201]
Related to #160 
Related to #44 
Related to #225 
Related to #493 

This is one of possibly many issues that will be opened to capture findings.

This issue is specifically a summary of findings from Google Play's APK upload / pre-launch reporting for **touch target sizes**:

- [ ] `mozilla​.lockbox:id​/button` = "Learn More" text button on settings
  "Consider making this clickable item larger."
  "This item's height is 21dp. Consider making the height of this touch target 48dp or larger."
  ![image](https://user-images.githubusercontent.com/49511/48363787-f9173a80-e663-11e8-8b90-188f226d044d.png)

- [ ] `mozilla​.lockbox:id​/cancelButton` = cancel the filtering text
  "Consider making this clickable item larger."
  "This item's size is 24dp x 24dp. Consider making this touch target 48dp wide and 48dp high or larger."
  ![image](https://user-images.githubusercontent.com/49511/48363826-14824580-e664-11e8-8524-28211e213ddb.png)

- [ ] `mozilla​.lockbox:id​/toggle` = settings switches
  "Consider making this clickable item larger.
  "This item's size is 47dp x 27dp. Consider making this touch target 48dp wide and 48dp high or larger."
  ![image](https://user-images.githubusercontent.com/49511/48363854-2cf26000-e664-11e8-909a-49e904b3d2a4.png)

- [x] `mozilla​.lockbox:id​/btnUsernameCopy` = copy button on list detail
  "Consider making this clickable item larger."
  "This item's size is 34dp x 34dp. Consider making this touch target 48dp wide and 48dp high or larger."
  ![image](https://user-images.githubusercontent.com/49511/48364034-94a8ab00-e664-11e8-8f50-49b8ce680b8f.png)

- [x] `mozilla​.lockbox:id​/btnPasswordCopy`
  "This item's size is 34dp x 34dp. Consider making this touch target 48dp wide and 48dp high or larger."
  ![image](https://user-images.githubusercontent.com/49511/48364047-a9853e80-e664-11e8-9cdb-b8ff439fad1c.png)

- [ ] `mozilla​.lockbox:id​/btnPasswordToggle`
  "This item's size is 34dp x 34dp. Consider making this touch target 48dp wide and 48dp high or larger."
  ![image](https://user-images.githubusercontent.com/49511/48364082-bd30a500-e664-11e8-8dd1-825b0b17abcd.png)

- [ ] `mozilla​.lockbox:id​/inputHostname`
  " This item's height is 43dp. Consider making the height of this touch target 48dp or larger. "
  ![image](https://user-images.githubusercontent.com/49511/48364155-f0733400-e664-11e8-8f69-5fe6f7cb9cb1.png)

- [ ] `mozilla​.lockbox:id​/buttonGetStarted` may be good to handle at #175 
  " This item's height is 36dp. Consider making the height of this touch target 48dp or larger. "
  ![image](https://user-images.githubusercontent.com/49511/48364132-ddf8fa80-e664-11e8-9423-4eab00312ca4.png)

**Comment by devinreams** [comment]
@mozilla-lockbox/ux I applied `needs-design` here as I think we should get your confirmation on which of these kinds of suggestions we do/not want to actually implement since they impact the app design.

I'll help review and reconcile with you all if you have some time to meet in the coming weeks...

**Comment by eliserichards** [comment]
These are all still accessibility issues (confirmed as part of #225). Definitely need some feedback from @changecourse if we're good to change these items.

**Comment by devinreams** [comment]
Stale. Closing in favor of #800
