### ISSUE TITLE
Change CI signing step to passthrough

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockwise/lockwise-android#209]
Note to self to test updating from the default zip option (zip: all) to passthrough from @g-k

https://github.com/mozilla-services/autograph/blob/master/signer/apk/README.rst#signature-request

https://bugzilla.mozilla.org/show_bug.cgi?id=1506598

AFAIK this may require some compression (not sure what Bitrise's build step is doing) first then a `zipalign` step after our sign step (in both the primary and deploy workflows): https://app.bitrise.io/app/20089a88380dd14d#/workflow

Related: having a gradle step to do the signing https://github.com/mozilla-services/autograph/issues/149

**Comment by eliserichards** [comment]
@devinreams is this still relevant?
