### ISSUE TITLE
"No Security" disclaimer should be shown when setting AutoLock in settings

### ISSUE THREAD

**Issue by sashei** [mozilla-lockwise/lockwise-android#219]
* If a user does not have a Pattern, PIN, or Password enabled on their device, this setting should default to "Never". Tapping this setting would then prompt the user to enable one of the device locking settings in order to change this 

**InVision**

No Screen Lock set: https://mozilla.invisionapp.com/share/3SN35UHWJDX#/328360848_Settings_-_Auto_Lock_-_No_Screen_Lock

**Zeplin**
No Screen Lock set: https://zpl.io/bPv9kgl

**Comment by sashei** [comment]
I think this feature is completed @devinreams @sandysage ?

**Comment by eliserichards** [comment]
This feature is already complete: 

<img width="391" alt="image" src="https://user-images.githubusercontent.com/43795363/64881705-18367e00-d621-11e9-9909-96c3edb66a51.png">
