### ISSUE TITLE
Lockbox crashes when trying to login on Android 6 devices

### ISSUE THREAD

**Issue by bsurd** [mozilla-lockwise/lockwise-android#243]
## Steps to reproduce

1. Open Lockbox on any Android 6 device
2. Tap on "Get Started"
3. Login with a valid username and password.

### Expected behaviour
The user is logged in and the entries screen is displayed.

### Actual behaviour
Lockbox crashes displaying "Unfortunately, Firefox Lockbox has stopped."

### Device and build information
- Nexus 5 (Android 6.0.1)
- HTC Desire 820 (Android 6.0.1)
- [Build #1316](https://app.bitrise.io/build/67245d12e783e79d)

### Notes
- Android 7, 8 & 9 devices do not seem to be affected by this
- [Logcat](https://github.com/mozilla-lockbox/lockbox-android/files/2623755/log.txt)
- [Video](https://drive.google.com/file/d/1HdIer9OaBpxo7sex2JqqHcFH58GW2rNN/view?usp=sharing)
- Retested with [build #1308](https://app.bitrise.io/build/b4c38f65356300aa), Lockbox crashes when tapping on get starded on that version, here is the [logcat](https://github.com/mozilla-lockbox/lockbox-android/files/2624086/log2.txt), this is the same for all other android versions as well

**Comment by devinreams** [comment]
@sashei has some ideas about this...

**Comment by sashei** [comment]
@bsurd thanks for the logcat file, that's really useful. I'm unable to repro this bug in an emulator unfortunately; would you mind confirming that deleting the app and re-installing results in the same error? it appears to be an issue with accessing the SQL database on the device, and I'm wondering if there was a corruption issue when upgrading between android-components versions. I'll keep working on reproduction locally.

**Comment by sashei** [comment]
On emulators for earlier versions of Android, I've encountered issues with login (consistent 500 errors?) among other things. As far as I can tell, these look like they're originating inside the `a-c` libraries themselves; I'm curious how much testing the app-services or `a-c` folks have done on different version of Android?

**Comment by sashei** [comment]
I found this issue in the application services backlog: https://github.com/mozilla/application-services/issues/197

It looks like they encountered this issue and tried a few workarounds, however, that was a while ago and we're still having issues :p I'd like to catch up with them tomorrow afternoon about this, but I wonder if we'd be better served by upping our minversion?

Open question @sandysage @devinreams @linuxwolf ....

**Comment by sandysage** [comment]
If we increase our minversion of support we're still covering ~50% of all of Android users. Given the stats we have for iOS and how most of our first users are likely 'early adopters' with newer devices, I'm inclined to start at Nougat (SDK 24) for our first launch. @linuxwolf do you agree?

**Comment by linuxwolf** [comment]
> If we increase our minversion of support we're still covering ~50% of all of Android users. Given the stats we have for iOS and how most of our first users are likely 'early adopters' with newer devices, I'm inclined to start at Nougat (SDK 24) for our first launch. @linuxwolf do you agree?

I don't have any objections.

**Comment by bsurd** [comment]
Tested with [build #1785](https://app.bitrise.io/build/8d9b6261fed6330c) and this is no longer reproducible on the initial devices I've tested with or any other devices.

@sashei From a QA standpoint, it's ok to close the issue if there isn't any more work that needs to be done here.

**Comment by JAicewizard** [comment]
I have a similar issue as described here on oneplus 5t android 9.0. I couldn't find any logcat logs (using on-device app) related to this crash. (using the Google play release version. Should I build lockbox myself and get logs via android studio?
