### ISSUE TITLE
Review file size and optimize for release

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockwise/lockwise-android#276]
Current Release build (1646) is about 70 MB. Worth going back and checking before release:

- assets are optimized
- not uncessarily including anything we don't need
- remove any duplicate stuff
- make sure test/debug stuff is excluded

**Comment by sandysage** [comment]
This is no longer critical as the current builds are much smaller. Keeping open to come back and optimize for fast follow releases.

**Comment by devinreams** [comment]
Assets were all just now optimize during the rebrand, but we should consider these two:

- Support multiple ABIs with separate APKs: #663 (now-ish)
- Android App Bundle: #544  (later)
