### ISSUE TITLE
Add support for biometric APIs to unlock app data

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockwise/lockwise-android#28]
When accessing Lockbox, I want to be able to use my fingerprint or device passcode instead of my password for security and convenience.

## Acceptance criteria
* Should be able to unlock with fingerprint or pin
* Should prompt for user consent/permission before using per the Android material design guidelines

## Tasks:
- [x] requires exploration #29
- [ ] launch biometric auth from WelcomeActivity
- [ ] successful auth dispatches unlock action

**Comment by sashei** [comment]
Curious if this might be best addressed in #68?
