### ISSUE TITLE
Biometric API exploration

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockwise/lockwise-android#29]
- [x] sample code to explore: https://github.com/linuxwolf/android-dataprotect
- [x] documented findings: https://mozilla-lockbox.github.io/lockbox-android/architecture/sec-apis/
- [x] user stories documented

**Comment by linuxwolf** [comment]
Prototyping code available in [android-dataprotect](https://github.com/linuxwolf/android-dataprotect).

**Comment by linuxwolf** [comment]
First-round of notes: https://github.com/linuxwolf/android-dataprotect/blob/master/README.md
