### ISSUE TITLE
[Marshmallow] Unable to complete FxA login redirect

### ISSUE THREAD

**Issue by 6a68** [mozilla-lockwise/lockwise-android#313]
Device info: Samsung Galaxy S5 / Android 6.0.1

When I click the 'Get Started' link in the latest pre-alpha build (bitrise build 1849), I see the following line in logcat:

```
12-21 08:42:28.352 22065-22065/? E/Log: Cannot route from 
mozilla.lockbox:id/fragment_welcome to mozilla.lockbox:id/fragment_fxa_login. 
This is a developer bug, fixable by adding an action to graph_main.xml
```

I am able to run through the FxA login process, then land at the Lockbox FxA Redirect page, but I'm not redirected back to the app, and nothing else shows up in logcat.

**Comment by eliserichards** [comment]
No longer valid. Fixed recently.
