### ISSUE TITLE
Refresh FxA access token if it's invalid

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockwise/lockwise-android#341]
When the FxA OAuth access token is invalid, the `LoginsStorage.sync()` method can throw a `SyncAuthInvalidException`, which should lead to Lockbox requesting a new token.  However, this error is not specially handled today.

**Comment by sashei** [comment]
According to the conversation on #337, we should both refresh the sync token and the profile information in this scenario.

**Comment by eliserichards** [comment]
Handled in #810 and #867
