### ISSUE TITLE
"No network issue" error although on network

### ISSUE THREAD

**Issue by bbinto** [mozilla-lockwise/lockwise-android#350]
STR:
- installed app, logged in, worked fine
- noticed I didn't have a great FxAccount password, went to Fx Account settings in Firefox to change password and enable 2FA as well
- now I can't login anymore with the new pwd
- "no network issue" error pops up (although on working wifi)

Pixel 2, Android version 9

Related to #356

**Comment by sandysage** [comment]
@eliserichards Can you tell me if this issue is now addressed with the #286?

**Comment by eliserichards** [comment]
Closing in favor of #373.
