### ISSUE TITLE
The login page is not displayed if turning the Internet ON after launching the app without Internet

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#361]
Relates to #373

## Steps to reproduce
1. Install lockbox.
2. Turn off the internet connection.
3. Launch Lockbox while the internet connection is still off.
4. Turn on the internet connection
5. Tap on "Get Started"

### Expected behavior
The Lockbox login screen is displayed after turning the internet connection on.

### Actual behavior
The Lockbox login screen is not displayed after turning the internet connection on.

### Device information
* Firefox Lockbox version: 1.0([build #2068](https://app.bitrise.io/build/5de084abff2a9e31))
* Samsung Galaxy Note 9 (Android 8.1.0)
* Google Pixel 3 XL (Android P/9)
* Samsung Galaxy S7(Android 7.0)
* Samsung Galaxy S8(Android 8.0)

### Notes
Note that even if tapping on the back button and then on "Get Started" without restarting the Lockbox, the login screen is still not displayed.
After restarting the Lockbox and tapping on the "Get Started" the login screen is displayed.
[Video](https://drive.google.com/file/d/1nmZvcPpTXMjTizAjTsQjbmSWGcoGMaSR/view?usp=sharing)
[logcat.txt](https://github.com/mozilla-lockbox/lockbox-android/files/2740816/logcat.txt)

Depends on #373

**Comment by devinreams** [comment]
@eliserichards this may possibly be worth testing against your work at #286 with networking error handling

**Comment by sandysage** [comment]
Assuming this gets addressed with #373

**Comment by eliserichards** [comment]
Closing as this is no longer applicable.
