### ISSUE TITLE
Splash screen - nessie image appears flattened on some devices

### ISSUE THREAD

**Issue by ioana-farcas** [mozilla-lockwise/lockwise-android#398]
The issue is more visible when after splash, welcome screen is displayed. 

I experienced this issue on Pixel 2, OS version 8.1.0. Also Nick saw it on Pixel 1. 
Was not reproducible on Samsung Galaxy S9, OS version 8.0

Follow up to #391

**Comment by deandreamatias** [comment]
I tried to reproduce the error in the text field on the login screen, but I usually work with my email.

Device: Huawei P10 Lite
OS: Android 8 API 26

**Comment by deandreamatias** [comment]
Was not reproduce this issue in Huawei P10 Lite, OS version 8.0

**Comment by eliserichards** [comment]
No longer applicable :)
