### ISSUE TITLE
Check whether "logins" are synced to user account, and offer to enable logins if not already

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla-lockwise/lockwise-android#403]
Because I used an external password manager, I explicitly disabled syncing logins and the Firefox built in login manager. To test Lockbox I enabled Firefox's login manager and saved a few passwords. When I opened Lockbox I was surprised to not see the logins that I saved. It took a minute to remember that I explicitly disabled the logins bucket in about:preferences#sync in Firefox desktop.

Is there a way for Lockbox to detect this and offer to enable sync for the logins bucket?

**Comment by eliserichards** [comment]
Closing as this is no longer applicable.
