### ISSUE TITLE
Re-opening app shows Get Started page

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-lockwise/lockwise-android#406]
### Steps to reproduce
1. Login and have an account setup
2. Close and swipe away the app
3. Re-open the app from the launcher

### Expected
- The unlock page/finger printer dialog should show up first

### Actual
- I see the 'Get Started' page for a few seconds, and then the unlock page.

### Device Information
OS: Android 9 (Pixel 2)
App version: 1.0

**Comment by eliserichards** [comment]
Closing as this is no longer applicable.
