### ISSUE TITLE
The welcome screen is displayed right after signing up with a new account instead of "All entries" screen

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#440]
## Steps to reproduce
1. Install lockbox.
2. Tap on "Get Started" and the enter your email.
3. Add all the required information in order to create a new account.
4. Verify the account and tap on `Continue`

### Expected behavior
The Lockbox login welcome screen is displayed.

### Actual behavior
The Lockbox entries screen should be displayed after the sign up.

### Device information
* Firefox Lockbox version: 1.0([build #2547](https://app.bitrise.io/build/1e77660644d82099))
* Sony Xperia Z5(Android 7.0)
* Samsung Galaxy Note 9(Android 8.1.0)
* Google Pixel 3 XL (Android P/9)

### Notes
Note that after sign up the devices is redirected to welcome screen and when tapping on the `Get started` the login screen is displayed without the password added(like the account is logged off).
After few seconds the login is successfully made and `All entries` screen is displayed.
`Note that the login is successfully made in the end, but is a little bit confusing when the welcome screen is displayed right after a sign up.`
[Video](https://drive.google.com/file/d/1A0bp7dIaO70VmWDj30gClr_RYK7bI-WO/view?usp=sharing)
[logcat.txt](https://github.com/mozilla-lockbox/lockbox-android/files/2865178/logcat.txt)

Related to #350

**Comment by eliserichards** [comment]
No longer valid.
