### ISSUE TITLE
Add a dark theme

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#454]
### Why/User Benefit/User Problem
A button that can switch from white to black theme should be implemented in the Lockbox for Android.
Like many other apps the dark theme is the most used theme(youtube/twitter..etc)
### What / Requirements
The white theme is the only one available now.
The dark theme will match the blue headers/menus from the Lockbox.
### Acceptance Criteria (how do I know when I’m done?)

**Comment by linuxwolf** [comment]
an article on supporting "day/night" themes in Android: https://medium.com/androiddevelopers/appcompat-v23-2-daynight-d10f90c83e94

**Comment by snorp** [comment]
Things are not good right now if you have the system-wide dark mode in Android 10 turned on.


![lockwise-dark](https://user-images.githubusercontent.com/31482/72448585-df4c1880-377c-11ea-96fe-b81736e2a311.png)

**Comment by abodea** [comment]
Hello @snorp thank you for adding this!
I added long time ago this one https://github.com/mozilla-lockwise/lockwise-android/issues/1072 and I do believe it's gonna be fixed in the next RC.
We had a fix for this the color was correctly displayed but it was a regression and a crash occurred when the search button was tapped.

**Comment by ddurst** [comment]
Should be fixed in https://github.com/mozilla-lockwise/lockwise-android/pull/1115
