### ISSUE TITLE
Open keyboard/numpad for user's when displaying the device auth screen to unlock Lockbox

### ISSUE THREAD

**Issue by nickbrandt** [mozilla-lockwise/lockwise-android#457]
Currently, when the device auth prompts are displayed to the user, the keyboard/numpad are not automatically displayed (user has to tap on field, even though it appears focused already). It would be nice to have those automatically shown (numpad for PIN, keyboard for Password), similar to the experience of unlocking your device.

There will probably need to be some exploration regarding this, as discussed [here](https://github.com/mozilla-lockbox/lockbox-android/pull/428#issuecomment-465679242)

**Comment by deandreamatias** [comment]
@nickbrandt Would you have the specific screen or image to exemplify where this feature could be implemented? Thank you

**Comment by changecourse** [comment]
@deandreamatias screens included... essentially our goal would be for the focus to be on the field by default, expanding the keyboard automatically when the page loads, though @sashei remind me, is there a potential issue in terms of being able to feasibly do this in our web view?

![FxA - Email - Keyboard Open](https://user-images.githubusercontent.com/6164801/55344053-9d5e1a00-5469-11e9-8f18-b80a765b1b44.png)
![FxA - Sign In - Keyboard Open](https://user-images.githubusercontent.com/6164801/55344054-9d5e1a00-5469-11e9-9606-67020bbc7c4d.png)

**Comment by deandreamatias** [comment]
@changecourse I understood. Maybe there is a solution. In a quick search, I've seen [this link](https://stackoverflow.com/questions/42872210/how-can-i-request-focus-to-specfic-text-field-in-webview).

**Comment by eliserichards** [comment]
Closing as this is no longer applicable.
