### ISSUE TITLE
Tapping Lock Now on first-time login will auto-prompt for device unlock

### ISSUE THREAD

**Issue by sashei** [mozilla-lockwise/lockwise-android#462]
### Steps to reproduce:
- Delete Lockbox and re-install
- Login using an FxA account or "Use Test Data"
- Navigate to the drawer
- Tap "Lock Now"

### Expected Behavior
The lock screen is shown, nothing else happens

### Actual
The lock screen is shown **and auto-prompts device authentication after one second.**

**Comment by sashei** [comment]
As far as I can tell, this only happens on first-time login. Every other use of the Lock Now button behaves as expected.

**Comment by eliserichards** [comment]
This has been fixed.
