### ISSUE TITLE
Autofills username but not password on paypal.com

### ISSUE THREAD

**Issue by pocmo** [mozilla-lockwise/lockwise-android#532]
Browsers:
 * Reference browser
 * Fenix

Lockbox: 1.0 (Is there a better number to report?) from test channel

I have Lockbox setup as my autofill provider. Whenever I visit paypal.com I see the autofill prompt. However it only autofills the username and never my password.

**Comment by devinreams** [comment]
I can confirm the same is true on 1.0.2 (3428) and likely due to how the website is semantically (or not) describing its password field. 😔

**Comment by eliserichards** [comment]
Paypal has a multi-screen login (enter your username, go to the next screen, enter your password). This feature has not been implemented yet. Will be done as part of #688.
