### ISSUE TITLE
Sign-in form has weird rending glitch with Android's copy/paste/etc. pop-up menus

### ISSUE THREAD

**Issue by callahad** [mozilla-lockwise/lockwise-android#535]
Android's text editing context menus show a weird white block behind them, as if they're not correctly compositing with the Lockbox content below.

![Screenshot from 2019-03-25 16-38-18](https://user-images.githubusercontent.com/24193/54939282-16b4b480-4f20-11e9-92ba-202510b8a628.png)

This may be an artifact of the Android Q beta, but I haven't seen it in any other apps.

Apologies for the low quality image; Lockbox doesn't allow screenshots.

**Comment by changecourse** [comment]
Thanks for catching this @callahad

We certainly don’t want to give the impression that something may be occurring in the web view that could be perceived as a phishing attempt. 

Suggesting we pull this into “On Deck” for exploration @ssage (github mobile isn’t letting me add tags)

**Comment by devinreams** [comment]
Also saw it on Pie. Not sure what we can do since its in the web view... may also be something FxA controls. Hmmm to investigate.

**Comment by eliserichards** [comment]
Fixed by #1036
