### ISSUE TITLE
Lockbox UI is broken after opening/resuming it again from Play Store

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#574]
## Steps to reproduce
1. Install and launch Lockbox.
2. Login with valid credentials.
3. Install the latest update from **`Play Store`**.
4. Open Lockbox from **`Play Store`**.
5. Reach the **`All Entries`** screen.
6. Multitask to **`Play Store`** and tap on the **`Open`** button.

### Expected behavior
Lockbox is resumed when tapping on the `Open` button from Play Store and everything works as expected.
### Actual behavior
**`All entries`** and **`Welcome screen`** are overlapped and the Lockbox menu cannot be reached as there is displayed the Lockbox **`Welcome screen`.**

### Device information
- Firefox Lockbox version: 1.0.1(3 April)
- Google Pixel 3XL(Android 9)

### Notes
Also note the following:
I was able to reproduce this [scenario](https://drive.google.com/file/d/1I38rRnLvClyphyX4P8utMfyUVXiApCLA/view?usp=sharing) but only few times and I can't figure out exactly the STR, the lockbox is stuck and no button for unlock appears only after a restart.
This issue ca be bypassed only with a restart.
For more details please see the [video](https://drive.google.com/file/d/1yrBF93_vewYBoFIm8cbxNJDEKM5OpW17/view?usp=sharing) and [logcat](https://drive.google.com/file/d/1wqiRsfSWAihPHOrZygJdqTxdm-NNlDMO/view?usp=sharing).

**Comment by MichaelKohler** [comment]
I can reproduce it reliably the following way:

* Open Lockbox, unlock it
* You see the entries
* Kill the app
* Open the app again
* You see the Welcome Screen without any option to unlock

![photo5857189241522597986](https://user-images.githubusercontent.com/330324/55682104-1653ea80-591e-11e9-85e8-a9c904685ff0.jpg)

* If you now wait until it self-locks (according to the setting), it will show the unlock button again and you can access the entries. However, steps above still apply after that.

Note: I'm using Lockbox Beta on Android 9, Nokia 5.

**Comment by devinreams** [comment]
I tried both approaches (force quit and open, force quite and open from store) on Pixel 2, Android 8. I did notice a "lag" that did not show the unlock button but it then cleared itself up and opened to the "All entries" screen.

@abodea @MichaelKohler are you still able to reproduce this?

**Comment by MichaelKohler** [comment]
Yep, seeing the same thing as you now, can't reproduce the complete lock and it behaves as it should. Of course, the minor lag could be improved, but that's a minor thing.

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on Lockwise 1.1.3 (Build 4584) using the following devices:
• Google Pixel 3XL (Android 9)
• Samsung Galaxy S8 + (Android 8)
• Samsung Galaxy S7 (Android 7)
