### ISSUE TITLE
Codecov in  seems to be broken

### ISSUE THREAD

**Issue by beatbrot** [mozilla-lockwise/lockwise-android#576]
Codecov on bitrise seems to be broken.

For reference, see [this](https://app.bitrise.io/build/77f52f2988195f34) build.

**Comment by devinreams** [comment]
As I understand it, for security reasons, bitrise completely prevents exposing "Secrets" in PRs from outside contributors/repos and I'm not sure of any workarounds at this time:

![Screen Shot 2019-04-08 at 10 23 55 AM](https://user-images.githubusercontent.com/49511/55740536-86c73e00-59e8-11e9-8566-2fdf7a471b46.png)

**Comment by beatbrot** [comment]
I guess it is okay like it is, I just wanted to inform you. But as you said, we should probably avoid the security risks that would be introduced by enabling this.

To sum it up: I can totally live with codecov being disable. Should I then close the issue or should I keep it open?

**Comment by devinreams** [comment]
Thanks again for reporting this @beatbrot. Looking at other projects, this security best practice (remove does mean it supersedes the ability to run codecov against contributor PRs).
