### ISSUE TITLE
Lockbox displays a mix between locked/logged in state

### ISSUE THREAD

**Issue by bsurd** [mozilla-lockwise/lockwise-android#580]
## Steps to reproduce
1. Login to Lockbox.
2. Minimize the app or press the task view button.
3. Open Lockbox again.

### Expected behavior
Your entries should be visible.

### Actual behavior
The welcome/lock screen is displayed with entries showing over it. 
The menu has no other options except for the lock now option.
The area above where half of the account image is displayed is scrollable.

### Device information
* Firefox Lockbox version: 1.0 [build #3334] from Play Store
* Nexus 6P (Android 8.1)

### Notes
* Didn't manage to reproduce on other devices. It might be specific to the 6P.
* [Logcat](https://github.com/mozilla-lockbox/lockbox-android/files/3053878/log.txt)
* [Video](https://drive.google.com/open?id=1mFot_HotnDuwCiex2pTfzxJAtJP2_AYt)

**Comment by eliserichards** [comment]
Closing - related to #582
