### ISSUE TITLE
Auto lock menu appears if left open when minimizing the app

### ISSUE THREAD

**Issue by bsurd** [mozilla-lockwise/lockwise-android#584]
## Steps to reproduce
1. Open Lockbox and go to Settings.
2. Open the auto lock menu.
3. Minimize the app and wait for the timer to pass.
4. Re-open the app.

### Expected behavior
The unlock screen is present.

### Actual behavior
The auto lock menu is overlaying the unlock screen.

### Device information
* Firefox Lockbox version: 1.0 [build #3334] from Play Store
* Nexus 6P (Android 8.1)
* HTC 10 (Android 8)
* OnePlus 5T (Android 9)

### Notes
* Seems to be #507 bun it's only reproducible for this specific scenario now.
* ![lock_menu](https://user-images.githubusercontent.com/17178945/55722497-27305900-5a0f-11e9-842a-3e83d38ea8be.jpg)

**Comment by devinreams** [comment]
I cannot reproduce this any longer (1.0.2 build 3428).

Opening after backgrounding and autolocking is showing me the "unlock" prompt and not the autolock timer setting screen.

**Comment by bsurd** [comment]
I am still able to reproduce this on some devices. (Samsung Galaxy S8, Lockbox version 1.0.2 build 3428 from Play Store).

The unlock screen is displayed if a lock is setup on your device but the auto lock menu is still displayed if tapping on the back button.

If setting a longer auto lock timer (eg 5 min+) opening the app after ~3min shows the auto lock menu over the "All entries" one.

**Comment by eliserichards** [comment]
Steps to reproduce:
1. Log in to Lockwise
2. Open the Settings menu, Autolock settings
3. Use the app switcher
4. See that the autolock menu stays open, and when foregrounding the app the menu stays above the item list

<img width="384" alt="image" src="https://user-images.githubusercontent.com/43795363/65087762-85794480-d97c-11e9-8183-7f4fa110e795.png">

**Comment by eliserichards** [comment]
No longer reproducible on v3.3.0 👍
