### ISSUE TITLE
Stuck on title screen without connection (e.g. airplane mode)

### ISSUE THREAD

**Issue by pocmo** [mozilla-lockwise/lockwise-android#596]
When starting Lockbox without having an internet connection (e.g. airplane mode) then it seems to only show the title screen and never open the actual app.

**Comment by RaheelJameel** [comment]
Indeed, I think the app does not currently support offline usage.
Offline usage is a very needed feature in my opinion, as not always you would have connectivity on your phone.

**Comment by eliserichards** [comment]
Closing as duplicate of #373
