### ISSUE TITLE
Error states and field validation for edit

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockwise/lockwise-android#603]
When I go to edit an existing credential, I want to know when I’ve either missed a required field or entered incorrect data. I don’t want to save information that isn’t useful to me when I next go to log into that account.

## Requirements
* Should detect and then serve an error message when nothing OR an invalid URL is entered into the web address
* Should detect and then serve an error message [Password cannot be empty] when nothing is entered into the password field
* Error messages should provide helpful guidance for correcting the data

## Visual Design

Zeplin: https://app.zeplin.io/project/5b6895bfe4af825140aa8dbc/screen/5c548fc49c3e07307b35a574
Invision: https://mozilla.invisionapp.com/share/3SN35UHWJDX#/screens/344499813

<img width="718" alt="Screen Shot 2019-07-11 at 9 26 13 AM" src="https://user-images.githubusercontent.com/6164801/61063897-04bb2c80-a3be-11e9-9fff-d1ba677db15f.png">

**Comment by isabelrios** [comment]
Moving this from QA Needed to Done. QA took a look at the feature landed on master and gave feedback about it. More testing will be done when the PI request arrives
