### ISSUE TITLE
[Parent issue] Manually create new entries

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockwise/lockwise-android#604]
When I have a credential that wasn’t created in the browser or didn’t save from the browser, I want to manually enter a new credential.

## Requirements
* Tapping the + from the entry list (android) opens the new entry screen - #821 
* Field validation + errors served on required fields in the new entry screen - #822 
* Confirmation required before discarding changes - #823
* No confirmation required if cancelling without making changes - #823 
* Display toast to confirm new entry creation (no designs yet) - #822

**Comment by sandysage** [comment]
@changecourse can we review what, if anything, we want to do for confirmation feedback when a new entry is created & saved?

**Comment by beatbrot** [comment]
May I ask what the tag "feature-CUD" means? :)

**Comment by changecourse** [comment]
@beatbrot it's [CRUD](https://en.wikipedia.org/wiki/Create,_read,_update_and_delete), minus the R, since we already have Read available :)
