### ISSUE TITLE
Rebrand to Lockwise

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockwise/lockwise-android#610]
[android icon assets.zip](https://github.com/mozilla-lockbox/lockbox-android/files/3104221/android.icon.assets.zip)

Zeplin: https://zpl.io/Vk5l0AZ
InVision: https://mozilla.invisionapp.com/share/3SN35UHWJDX
Rollout plan: https://docs.google.com/document/d/1U-Rqu4WZAYrLbwPeTM8F32Zwg67ymEq9CSRjhQ2w2Ec/edit

**Comment by devinreams** [comment]
Branch created:
https://github.com/mozilla-lockwise/lockwise-android/tree/610-rebrand
