### ISSUE TITLE
Error message `Result::unwrap()` on an `Err` value

### ISSUE THREAD

**Issue by 687766616e** [mozilla-lockwise/lockwise-android#611]
![IMG_20190423_015809](https://user-images.githubusercontent.com/20995449/56515769-47adf680-656b-11e9-9481-df38c0b1c214.jpg)

**Comment by huitc** [comment]
android 8.0.0
xiaomi mi6
app version: 3334

**Comment by eliserichards** [comment]
Possibly helpful: https://github.com/rust-lang/rust/issues/54900

**Comment by vladikoff** [comment]
If there is Sentry or something hooked up, we would need to see the stack from the PoisonError

cc @thomcc

**Comment by eliserichards** [comment]
Closing this as invalid for now - if we see this again we can reopen.
