### ISSUE TITLE
Create a generic error handler for subscriptions

### ISSUE THREAD

**Issue by eliserichards** [mozilla-lockwise/lockwise-android#622]
**Purpose**: create a generic error handler for our Rx subscriptions which can be implemented by default. This will minimize the amount of manual error catching.

Suggestions: 
* Overload the `catch` operator http://reactivex.io/documentation/operators/catch.html

**Comment by devinreams** [comment]
Since we have over a dozen crashes with these exceptions not handled, this may be a good candidate for a P1 and have promoted to "On Deck" to consider during a triage soon.

**Comment by devinreams** [comment]
After talking it over, this is better suited to actually catch and handle all the errors...
