### ISSUE TITLE
Delete an entry from the entry edit view

### ISSUE THREAD

**Issue by sashei** [mozilla-lockwise/lockwise-android#630]
Depends on #626 
Depends on #628

## Requirements

- Should provide the ability to delete an entry from the entry edit view
- Deleting the entry routes back to the list view

## Visual Design
**Zeplin**
Edit entry layout - https://zpl.io/boDxOPX

**Invision**
Edit entry layout - https://mozilla.invisionapp.com/share/3SN35UHWJDX#/screens/344499813

**Comment by isabelrios** [comment]
@eliserichards can we close this issue? It is under the QA-ready column but no QA is needed (I think) and the feature described is implemented, we could keep open the issue related #904

**Comment by eliserichards** [comment]
This can be closed. Added to #843.
