### ISSUE TITLE
Opening a website from entry details requires two "back" taps after returning to Lockbox

### ISSUE THREAD

**Issue by sashei** [mozilla-lockwise/lockwise-android#646]
steps to reproduce:
- open a website from an entry detail screen
- return to Lockbox (device back button, app switcher)
- tap back once on the entry detail

**expected**
the app navigates back to the item list

**actual**
the app stays on the entry details and requires a second "back" tap to return to the item list

**Comment by faogustavo** [comment]
You can also reproduce this one by just:

* open the entry detail screen
* put the app in the background
* return from background

The issue is that the `AppRoutePresenter` is running the last state from RouteStore again when the app is active again.
