### ISSUE TITLE
Bug #1548367 - sessionToken on disconnect

### ISSUE THREAD

**Issue by eliserichards** [mozilla-lockwise/lockwise-android#648]
https://bugzilla.mozilla.org/show_bug.cgi?id=1548367

Relies on invalidate_session_token method in app-services.

depends on https://github.com/mozilla/application-services/issues/1139

**Comment by devinreams** [comment]
This is effectively unblocked per @linuxwolf @sashei @eliserichards 

A separate "improved way to sign out" using https://github.com/mozilla/application-services/issues/1139 should be considered.
