### ISSUE TITLE
KotlinNullPointerException on FingerprintAuthDialogFragment$resetErrorTextRunnable$1.run

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockwise/lockwise-android#651]
To look into after #165 

This is now the biggest category of crash appearing in Google Play Console

https://play.google.com/apps/publish/?account=7083182635971239206#AndroidMetricsErrorsPlace:p=mozilla.lockbox&appid=4972100280256015711&appVersion=3428&clusterName=apps/mozilla.lockbox/clusters/882a0c93&detailsAppVersion=3428&detailsSpan=7

... and Sentry. There are two of these but seemingly on different lines (105, 72):

https://sentry.prod.mozaws.net/operations/lockbox-android/issues/5586928/
https://sentry.prod.mozaws.net/operations/lockbox-android/issues/5602110/

```
KotlinNullPointerException: None
    at mozilla.lockbox.view.FingerprintAuthDialogFragment$resetErrorTextRunnable$1.run(FingerprintAuthDialogFragment.kt:105)
...
(3 additional frame(s) were not displayed)
```

```
mozilla.lockbox.view.FingerprintOnboardingFragment$resetErrorTextRunnable$1 in run at line 72
```

**Comment by devinreams** [comment]
The other related Sentry issue: [LOCKBOX-ANDROID-X](https://sentry.prod.mozaws.net/operations/lockbox-android/issues/5602110/)

**Comment by devinreams** [comment]
To look into after #165

**Comment by eliserichards** [comment]
There has only been one report in the last two months. Closing this as no longer valid.
