### ISSUE TITLE
String interpolation on "Enable Fingerprint" dialog

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockwise/lockwise-android#658]
Both on 1.0.3 and the in-progress rebrand branch does not show the product name in the "permission to unlock the app with the fingerprint sensor" string:

![IMG_2700](https://user-images.githubusercontent.com/49511/57466875-af886080-723e-11e9-9204-8cab636d15f1.JPG)

Since this is minor, it'd be nice to get in as part of the 1.0.3 release (QA will be done tomorrow with any other release blockers/bugs).

**Comment by faogustavo** [comment]
Just opened a PR. hope it helps.
