### ISSUE TITLE
Onboarding confirmation screen delay

### ISSUE THREAD

**Issue by eliserichards** [mozilla-lockwise/lockwise-android#673]
Currently, when someone is on the Autofill onboarding screen, and then goes to set their autofill provider via the "Go to Settings" button, the Confirmation "You're all Set" overlay is displayed before the app switches them to the settings screen... 

Ideally, we would stay on the Autofill screen until they choose Lockwise as an autofill provider, and only navigate to the "You're all set" confirmation once they've been successfully routed back to Lockwise. 

Alternatively, we could set a delay on the button for "Go to Settings" so that the confirmation screen is triggered after they've already been switched to the settings screen for autofill, though this may cause unforeseen issues... not sure.

**Comment by devinreams** [comment]
@changecourse @eliserichards I lost the context of this bug. Is there a problem that there is a delay? Or we should put something between the instructions and the confirmation screen?

Currently assigned/blocked by UX, please feel free to correct me/elaborate if we have what we need to make a change.

**Comment by eliserichards** [comment]
Confirmed with @changecourse in slack that this can be deprioritized in favor of our current priorities for this sprint (security bugs & autofill save).

**Comment by faogustavo** [comment]
@eliserichards The expected behavior is to show the "You're all Set" screen even if the user doesn't change to Lockwise?
