### ISSUE TITLE
Android lint should ignore missing translations

### ISSUE THREAD

**Issue by Pike** [mozilla-lockwise/lockwise-android#675]
Right now, adding localizations to lockwise breaks the linter, as we have non-localizable strings outside of `strings.xml`.

In general, it'd be nice to just build with missing strings, they might not be all that bad, and we want to test what we have, too.

That's what Fenix did in https://github.com/mozilla-mobile/fenix/pull/1560

This blocks merging string imports, aka #674 

CC @Delphine

**Comment by devinreams** [comment]
Closed and confirmed ✅ at #674
