### ISSUE TITLE
Lockwise logo is displayed under entries after resuming it

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#698]
### Steps to reproduce
1. Launch lockwise.
2. Login with valid credentials.
3. While being on the entries list put lockwise on background.
4. Resume lockwise.
### Expected behavior
Entries list is correctly displayed and no visual issues are present.
### Actual behavior
The lockwise logo are displayed under the entries list,
### Device and build information
* **`Google Pixel 3(Android 9)`**
*  **`Lockbox version: 1.1.0 (3951)`**
### Notes
This issue occurs only after resuming Lockwise, after entering any account, the lockwise logo will disappear.
For more details please see the attachment: [video](https://drive.google.com/open?id=1sRQWTc3Vr7lJSZN7cPVCKaATHYp06Nvr)

**Comment by devinreams** [comment]
I believe this is similar enough it may be the same as #699 where the launch screen / theme is getting set in places it shouldn't/wasn't before. 🤔
