### ISSUE TITLE
Two Lockwise logos are displayed instead of the settings menu after resuming it

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#699]
### Steps to reproduce
1. Launch lockwise.
2. Login with valid credentials.
3. While being on the entries list put lockwise on background.
4. Resume lockwise.
5. Tap on the hamburger menu in order to reach settings menu.
### Expected behavior
Settings menu is displayed with all the options.
### Actual behavior
The lockwise logo are displayed instead of settings menu.
### Device and build information
* **`Google Pixel 3(Android 9)`**
*  **`Lockbox version: 1.1.0 (3951)`**
### Notes
This issue occurs only after resuming Lockwise, if entering any other menu, this will disappear.
For more details please see the attachment: [video](https://drive.google.com/file/d/1XNBAihmkD3bJfeZIAQhnYBFQRrg68kW4/view?usp=sharing)

**Comment by devinreams** [comment]
Ah I think I've seen this before too. Another workaround is to Lock Now and then unlock and it appears to clear up. Would be good to figure out the cause of falling into this state after backgrounding, though.
