### ISSUE TITLE
Consolidated Logic to Determine Device Security Stance

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockwise/lockwise-android#70]
Use the KeyguardManager to determine if the user's device is secured using a Pattern/PIN/Password, and the FingerprintManager to determine if fingerprint hardware is available and at least one fingerprint is enrolled.

This detection happens during:

* Onboarding to help configure a higher security stance within the app
* Settings to determine what configuration options are available

**Comment by devinreams** [comment]
Some of this is happening in #68 and #64 (in that order)

May be close-able once those are landed

**Comment by sandysage** [comment]
@linuxwolf would you mind taking a look to see if we're good to close this issue or if we need to do something else here?

**Comment by sashei** [comment]
@linuxwolf ping :)

**Comment by sashei** [comment]
Let's call this resolved unless we need any further documentation.
