### ISSUE TITLE
The FAQ/Privacy/Provide feedback are not updated as the examples/texts are still about Lockbox

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#700]
1. Install and launch lockwise.
2. Access FAQ from any menu where it is available.

### Expected behavior
FAQ is updated with all the new tutorials regarding Lockwise.
### Actual behavior
The old FAQ is still displayed pointing about Lockbox.
### Device and build information
* **`Google Pixel 3(Android 9)`**
*  **`Lockbox version: 1.1.0 (3951)`**
### Notes
For more details please see the attachment: 
![20190524_124518](https://user-images.githubusercontent.com/42831109/58319098-db503c80-7e21-11e9-9eae-e219f3bc3f17.jpg)

**Comment by devinreams** [comment]
Thanks @abodea we're launching these sites/materials separately such as at:
https://github.com/mozilla-lockwise/mozilla-lockwise.github.io/pull/117
