### ISSUE TITLE
White box is displayed around long-press menu in webviews

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#701]
1. Install and launch lockwise.
2. Login with valid credentials.
3. Access the settings menu.
4. Access **`Provide Feedback.`**
5. Scroll down until nr.4 and tap on the text field and type anything.
6. Tap and hold on the text.

### Expected behavior
The "Copy, Cut, Paste, Clipboard, Autofill" custom menu is displayed and text selector without problems.
### Actual behavior
A white box square is displayed around(**`cut, copy, paste and select all`**) buttons and text cursor.
### Device and build information
* **`Google Pixel 3(Android 9)`**
*  **`Lockbox version: 1.1.0 (3951)`**
### Notes
For more details please see the attachment: 
![20190524_152205](https://user-images.githubusercontent.com/42831109/58327343-047bc780-7e38-11e9-84cc-9cc59aef8d00.jpg)

**Comment by eliserichards** [comment]
This is also reproducible on the FxA login webview.

**Comment by AndiAJ** [comment]
I've also noticed that on v1.1.3 Build 4584 using a Google Pixel3XL (Android 9) phone that there's a movement issue as well.
[►Video](https://drive.google.com/open?id=1K3tohec3MlCo4Tsuhpx3QsU83kcPMsW4)

**Comment by eliserichards** [comment]
Related to #535

**Comment by eliserichards** [comment]
Will be fixed by #1036

**Comment by abodea** [comment]
Verified as fixed on **`3.2.0 (Build 5522)`** with **`Google Pixel 3a XL(Android 10).`**

**Comment by eliserichards** [comment]
Fixed in #1061
