### ISSUE TITLE
Cannot login with account age under 14 in FxA webview

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#703]
1. Install and launch lockwise.
2. Add an email in order to register it.
3. On the `AGE` field put `-1`.
4. Tap on create account.

### Expected behavior
The user is informed that the age must be above 14 years old(I think this is the limit) with a lock screen but also with a option to logout or login with another account.
### Actual behavior
Lockwise is stuck and any other login cannot be made.
### Device and build information
* **`Google Pixel 3(Android 9)`**
*  **`Lockbox version: 1.1.0 (3951)`**
### Notes
Please note that this issue occurs when adding any age below 14 yrs old.
Also, note that sometimes this issue doesn't disappear after restarting lockwise.
[video](https://drive.google.com/file/d/1YV8LeTROXBQP_s5LVMWwgHhCxamlvxKT/view?usp=sharing) and [logcat.txt](https://github.com/mozilla-lockwise/lockwise-android/files/3217170/logcat.txt)

**Comment by NgoHuy** [comment]
I cannot login in LockWise with 2FA.

**Comment by abodea** [comment]
Hi @NgoHuy can you provide more steps regarding your issue?

**Comment by NgoHuy** [comment]
@abodea I enabled 2FA on firefox accounts, then I login with same password on LockWise, it returned me to get started page.

**Comment by NgoHuy** [comment]
oh sorry @abodea I type wrong password then email to alert me.

**Comment by abodea** [comment]
@NgoHuy no problem, even if this was still persisting for sure would be other issue separated of this. 

Have a nice day,
Andrei

**Comment by NgoHuy** [comment]
I confirm that I can login with 2FA.

**Comment by shane-tomlinson** [comment]
Blocking users that are 13 or under is a hard requirement from legal so that we do not fall afoul of COPPA - https://www.ftc.gov/enforcement/rules/rulemaking-regulatory-reform-proceedings/childrens-online-privacy-protection-rule

**Comment by ddurst** [comment]
In fact, this "dead end" state -- for FxA -- is saved in a session cookie, so we intentionally don't want the user to be able to simply start over. Anything we would do here to allow that provides a way for a user to bypass that.
