### ISSUE TITLE
Both password fields are revealed in FxA webview

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#704]
### Steps
1. Install and launch lockwise.
2. Add passwords on the fields.
3. Tap on the `See password` button.

### Actual behavior
Even if tapping on the first or second button, both passwords will be displayed and the other button will be selected by default.
### Expected behavior
If there are 2 buttons for password preview, each button should trigger the individual password for each field.
### Device and build information
* **`Google Pixel 3(Android 9)`**
*  **`Lockbox version: 1.1.0 (3951)`**
### Notes
For more details please see the [video](https://drive.google.com/file/d/1HYXVqtYVX_cqlWgLpzstPkoKE-qifbSO/view?usp=sharing).

**Comment by shane-tomlinson** [comment]
Is this the signup page? If so, this is the expected behavior, more context can be found in https://github.com/mozilla/fxa-content-server/issues/3600

**Comment by ddurst** [comment]
^ @abodea

**Comment by abodea** [comment]
Hello and sorry for the late response!
Yes this is the singup page. If this is the intended behavior based on my comment and Shane comment I will close this issue.
