### ISSUE TITLE
Logins not syncing after install

### ISSUE THREAD

**Issue by DanielValahul** [mozilla-lockwise/lockwise-android#711]
Hello, 
I have tried to use the Lockwise (version 1.10) app as a login manager on Android. However, it doesnt seem to sync anything. After login it just displays the "Syncing your logins" message on the bottom but nothing happens, no matter how long I wait.
Is there any fix for it or is it a bug? 
I have already tried uninstalling&reinstalling it, clearing the data and force stopping it but it doesnt seem to have any effect on it. 
I should also add that the old app (Lockbox) never worked as well, for some reason it always got stuck at syncing the logins

**Comment by devinreams** [comment]
Hey @DanielValahul we suspect this is a bug and one we're still trying to reproduce ourselves. Thaks for your report and attempts at troubleshooting.

We may circle back here to ask more questions if you're up to help us out a bit more. Thanks again.

**Comment by pedro7** [comment]
I have a logcat of looking ten minutes for a syncing screen.
Shall I attach here a grep [lockwise|lockbox] ?
Which info should I redact first?

**Comment by pedro7** [comment]
[filtered-20190528.zip](https://github.com/mozilla-lockwise/lockwise-android/files/3232388/filtered-20190528.zip)

**Comment by devinreams** [comment]
Thanks everyone for your reports.

Mitigation and data collection starting with next release, and some improvements planned at #716

**Comment by pedro7** [comment]
Lockwise is now working for me on version 1.1.1 (4053) :)
I also installed the Lockwise Firefox Add-on in the meantime (don't know if it can be related to the app starting to work).

**Comment by pwd-github** [comment]
Just tested with 1.1.1 with the add-on installed on my desktop. I still got the error.

**Comment by devinreams** [comment]
Version 1.1.2, which is available to Beta testers and will be live to all users soon, should resolve this (I personally haven't encountered it again in my own testing).

Once you have the update, please let us know if it's still happening for you...

**Comment by TenSeventy7** [comment]
Hi. I'm still experiencing the same issue on 3.3.0. Galaxy A50, Android 9.0.

**Comment by lopezator** [comment]
Same happens for me, "Syncing your logins" takes forever but doesn't sync anything.

My phone is Android One. Xiaomi A2, Android 9.

**Comment by lopezator** [comment]
@devinreams how can i join that beta tester group? I'm using this app extensively.

**Comment by mrsarm** [comment]
Same problem me, using latest version available on Play store for Android.

**Comment by mrsarm** [comment]
Has the same issue also in the smartphone of my wife, Android 9 and Android 10 devices.

To solve the issue I needed to clean the app data from the "Applications" section in the Android settings, and start again the synchronization. After that in both devices the app is working great again and synchronize each change very quickly.

**Comment by zjeffer** [comment]
Same issue here, Android 10 on Oneplus 6. 

@devinreams Please reopen this issue as the bug is still present. @mrsarm's solution worked for me.

**Comment by htsmi** [comment]
Same issue on Android 10 on Moto X4. Had been working reliably for several months and now no passwords. It may have been preceded by an app update.

Why was this issue closed?

I think I will try an offline password manager since I can't really afford to have everything disappear randomly.

**Comment by catskul** [comment]
Having this issue on 4.0.3.
