### ISSUE TITLE
Sync timeout

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockwise/lockwise-android#716]
Right now when Sync doesn't complete, someone is in a stuck state with the Sync spinner. Opening this ticket as a mitigation until there is a fix from A-S.

Ideal: show a toast that informs the user that Sync timed out (would need localization). otherwise boot to 'no entries' found.

- [x] investigate where/why we wouldn't get a timeout error from a-s
- [x] introduce a timeout in sync (so no infinite spinner)
- [x] catch this condition and log it to sentry
- [x] show an empty state with a message
  - "Syncing has timed out."

**Comment by eliserichards** [comment]
Sync timeout is added as part of #708 in the `sync` method of the DataStore:

```
backend.sync(syncConfig)
            .asSingle(coroutineContext)
            .timeout(Constant.App.syncTimeout, TimeUnit.SECONDS)
            .doOnEvent { _, _ ->
                syncStateSubject.accept(SyncState.NotSyncing)
            }
            .subscribe(this::updateList, this::pushError)
            .addTo(compositeDisposable)
```
