### ISSUE TITLE
When trying to search the apps attempts to sync again infinitely

### ISSUE THREAD

**Issue by Bandito11** [mozilla-lockwise/lockwise-android#733]

**Comment by Bandito11** [comment]
1. Start the app
 2.   App sync logins
3.    Attempt to search
  4.  It syncs again

**Comment by devinreams** [comment]
Quick triage: we have experienced but cannot consistently reproduce this with just these steps, we need to figure out what the condition is causing this. We'll see if we or others in QA can help.

P1 since it renders the UX un-usable, but need help getting it reproduced.

**Comment by Bandito11** [comment]
Hi
This was fixed in a subsequent update.

**Comment by abodea** [comment]
I re-checked this issue but couldn't reproduce it on the latest build **4.0.0 (Build 6087)**.
Based on the comment from above and my comment I will remove the `needs-reproduce` label.
