### ISSUE TITLE
Trying to edit or search for passwords in-app causes it to start syncing

### ISSUE THREAD

**Issue by DanielValahul** [mozilla-lockwise/lockwise-android#736]
Hello,
Lockwise 1.1.1 solved the problem of Lockwise not syncing (at least for me), but it appears a new bug has surfaced. 
If I try to edit or search for a password inside the app, Lockwise will close the menu and start to sync, thus no changes can be made and no searches can be done.
I already tried to clear cache, force stop or reinstall the app.
Please feel free to ask me for details if its necessary, I tried to be short and concise.

**Comment by devinreams** [comment]
Duplicate of #733

Discussed with the team and "merging" into that. Thanks @DanielValahul
