### ISSUE TITLE
Change the packageName :mozilla.lockbox to :mozilla.lockwise

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#739]
### Steps
1. Install and launch Lockwise.
2. Connect the device to a PC and observe the logcat.
### Expected results
The **`packageName`** should be **`:mozilla.lockwise `**.
### Actual results
The **`packageName`** is **`:mozilla.lockbox`**.
### Device and build information
* **`Samsung Galaxy Note 9(Android 8.1)`**
*  **`Lockwise version v1.1.1 (Build 4053) `**
### Notes
This is also present on the Play Store webpage https://play.google.com/store/apps/details?id=mozilla.lockbox.
![download (8)](https://user-images.githubusercontent.com/42831109/58945220-193b5200-878c-11e9-8f59-7d1b3a9f7770.png)
![download (9)](https://user-images.githubusercontent.com/42831109/58945243-25271400-878c-11e9-9d5e-345bb8cd0b0e.png)
And here you can find the logcat [logcat_packageName.txt](https://github.com/mozilla-lockwise/lockwise-android/files/3256423/logcat_packageName.txt).

**Comment by sblatz** [comment]
If this is updated, please notify the Fenix team so we can [update our telemetry](https://github.com/mozilla-mobile/fenix/issues/1192)

**Comment by abodea** [comment]
@sblatz sure thing, once this will be updated I will re-check the [1192](https://github.com/mozilla-mobile/fenix/issues/1192) and add the results.

**Comment by linuxwolf** [comment]
We are deliberately excluded package names from the rebranding effort.
