### ISSUE TITLE
Create a new Firefox account from Lockbox

### ISSUE THREAD

**Issue by leobel96** [mozilla-lockwise/lockwise-android#744]
In my opinion the app should be made independent of Firefox so that the users that don't want to use Firefox as primary browser could rely on a good, fresh, open and secure password manager. To do it the possibility to create new entries is required (https://github.com/mozilla-lockwise/lockwise-android/issues/604#issue-435216255) and also the possiblity to create a new account.

**Comment by eliserichards** [comment]
Closing in favor of our #feature-cud work :)
