### ISSUE TITLE
Lens icon cut

### ISSUE THREAD

**Issue by leobel96** [mozilla-lockwise/lockwise-android#745]
I've noted in the last update (1.1.1, anyway I don't know if it was present before) that the lens icon used to search is cut (maybe "Tutte le credenziali (A-Z)" is too long). I attach a photo of the issue. Nokia 7 plus, Android Pie 9.0.

![2019-06-06-211402](https://user-images.githubusercontent.com/19806799/59060086-97891880-88a0-11e9-99bb-da88b8ae3309.jpg)

**Comment by Spinus1** [comment]
In my P9 lite with Android 7.0 the lens icon is completely hidden...

**Comment by devinreams** [comment]
Thank you for your reports. This has also been reported and addressed at #737 #728 and should be fixed in the next release (1.1.2).
