### ISSUE TITLE
Filling hidden username form field with emtpy username

### ISSUE THREAD

**Issue by betatim** [mozilla-lockwise/lockwise-android#758]
Hi 👋 !

Really like using Lockwise and bumped into this oddity: I have a form that only asks for a password and Lockwise/Firefox correctly shows "no username" in the app. When I tell it to autofill the form and then press submit I get "wrong password" back from the server.

The problem turns out to be that this particular form has a hidden field called `username` that contains "something set by the server" and should be left alone. However when I inspect the request POST'ed I see that the username parameter is set to `""` (the empty string). My guess is that Lockwise fills in the form field with the "empty username" value.

I think this is a pretty weird form, so I am not sure what Lockwise should do here. Maybe checking if a form field is visible/hidden before filling it would be a way forward. Not sure I can think of a case where there are invisible (to humans) form fields that the website would expect me to fill in.

I am actually not sure if this should be a Lockwise ticket or is a more general Firefox form filling with credentials issue. If you could let me know that would be great.

App version: 1.1.1 (4053)
Firefox beta 68.0b7
Android version 9

**Comment by eliserichards** [comment]
Great find @betatim! We'll take a look at this and update here 😄

**Comment by jhugman** [comment]
Hi, @betatim 

Thanks for your report. Would you be able to share which login page/app you are filing this issue for?

This server seems to be setting the username field explicitly and to detect if the client (the user-agent, including password manager) have filled in the username.

Thus, I think there are potentially two of three problems here: 

 1. the username shouldn't be filled in by lockwise if it is not in the database
 2. empty usernames shouldn't be written to the database— currently not an issue
 3. the server is not expecting a username in the hidden field. I am hoping that the server would accept a valid username OR not mutating it all, but it would be good to get the page from you so I can verify.

Fixing 1. is definitely a bug which should be verified.

**Comment by betatim** [comment]
Hey,

just tested it again and can't reproduce it any more.

For debugging:

[This is the site](https://ais-sas.swisscom.com/sas/web/tkd6a6bcf9e9ed4b6fb897626c7af7fe2ctx/pass-check?lang=en) and the source of the site is in https://gist.github.com/betatim/108e568f77151e916fd71fe914f7c5a2. It is part of a 2FA setup to confirm you want to electronically sign a document. When I originally set the password it was on a slightly different page/not part of the flow of pages that are used when I use the password manager.

This time when I selected the password from the drop down below the input field lockwise suggested "no username" and left the hidden username value unchanged. Which then got POST'ed to the action of the form. 

As far as I can tell the username is different each time you request the verification.

Unfortunately you can't sign up to use the service just like that, you need an account that you can only get by meeting someone in person to verify your identity via an ID document (if you ever happen to visit Zurich in Switzerland let me know ;) ).

As the problem has gone away I think we should close this now unless you want to debug some more.
