### ISSUE TITLE
Can't see details/password, keeps loading main with syncing

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla-lockwise/lockwise-android#762]
## Steps to reproduce

1) Open app, unlock and wait until synced
2) Click on any entry to get the detail view

### Expected behavior

I see the details and can copy the password.

### Actual behavior

Keeps reloading the main view ("syncing"). I can't copy my password. The same happens when I want to search.

### Device & build information
* Device: Nokia 5, Android 9
* Build version: latest Play Store version
### Notes
Attachments:

**Comment by Neikon** [comment]
If you click in search icon, you get a infinite loading too
Device : OnePlus 7, oneplus 3, Android 9
Build version: latest Play Store version

**Comment by eliserichards** [comment]
Closing in favor of #892.
