### ISSUE TITLE
Strange behavior from "Get Started" reset password or remember password buttons

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#778]
## Steps to reproduce
1. Launch Lockwise.
2. Reach the `Get started` screen where you can reset your password.
3. Tap on "Begin Reset" and then on "Remember Password?Sign In" 
### Expected behavior
When returning to the screen where you can add the password everything looks as expected.
### Actual behavior
When returning to the screen where you can add the password, there is a white big box and the text can be selected and zoomed in.
### Device & build information
* **`Samsung Galaxy s10+(Android 9)`**
*  **`Lockwise version 1.1.2 (Build 4342) `**
### Notes
Attachments: [Video](https://drive.google.com/file/d/14S94Q8FK2dqOnQCqNP7s_uM_SpfB69U6/view?usp=sharing)

<img width="274" alt="image" src="https://user-images.githubusercontent.com/43795363/65109738-0ac12100-d99e-11e9-9884-9d042208d13d.png">

**Comment by eliserichards** [comment]
Custom tabs could be used here, possibly.

**Comment by eliserichards** [comment]
Fixed by #1036
