### ISSUE TITLE
Lockwise crashes/added to background after changing to an unsupported language

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#783]
## Steps to reproduce
1. Launch Lockwise.
2. Login with valid credentials.
3. Reach the entries menu.
4. Change the language to an unsupported one.
5. Resume Lockwise and wait.
### Expected behavior
The `English` language is displayed in Lockwise and no other issues are present.
### Actual behavior
Lockwise crashes/added to background after changing to an unsupported language.
### Device & build information
* **`Samsung Galaxy s10+(Android 9)`**
*  **`Lockwise version 1.1.2 (Build 4342) `**
### Notes
Attachments: [Video](https://drive.google.com/open?id=1l7BxIAGthE2GkiiZsYFgaEprrFu16oKW)
[log_crash.txt](https://github.com/mozilla-lockwise/lockwise-android/files/3329459/log_crash.txt)

**Please note that I'm not very sure if this is a crash I couldn't find out from the logcat, but it looks like one.**

**Comment by eliserichards** [comment]
Not reproducible on latest build on Pixel 3. Needs to be reproduced on other devices.

**Comment by abodea** [comment]
I tried to reproduce it but with not so much success using the latest Lockwise version 1.1.3 with Samsung Galaxy s10+(Android 9).
Based on Elise comment and mine I will close this issue, in case I will reproduce this issue I will re-open it.
