### ISSUE TITLE
Remove Sync timeout

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-lockwise/lockwise-android#791]
## Steps to reproduce
1. Open Lockwise and login with a Mozilla account that has saved logins.
2. Drag down from the top of the screen in order to trigger the sync.

### Expected behavior
The saved logins from the Mozilla account should be displayed.

### Actual behavior
The "Syncing has timed out error" is displayed and the logins are not retrieved.

### Device & build information
* Device: Samsung Galaxy S9 (Android 8.0.0)
* Build version: Lockwise version 1.1.2 (Build 4342)

### Notes
The issue only occurs when using the account laursv52@mailinator.com pass: softvision
Attachments: 
![Syncing has timed out error is displayed constantly](https://user-images.githubusercontent.com/50983519/60181246-76c23c00-982a-11e9-82d7-c3e3beaf7b4e.gif)
[logcat.txt](https://github.com/mozilla-lockwise/lockwise-android/files/3330073/logcat.txt)

### Eng todo
- [ ] add telemetry around timeout

**Comment by abodea** [comment]
Please note that this is the only device that had this issue, on others everything worked correctly.

**Comment by eliserichards** [comment]
This should be fixed with Sasha's PR #756.

**Comment by isabelrios** [comment]
> This should be fixed with Sasha's PR #756.

Great! I was about to comment that this is happening to me on Pixel 3 with Lockwise 1.1.2 whenever I try to refresh my logins list.
Thanks!

**Comment by devinreams** [comment]
>>This should be fixed with Sasha's PR #

>I was about to comment that this is happening to me on Pixel 3 with Lockwise 1.1.2

Oh hmmm, then I think this issue is saying its still a problem since the testing was against builds that already included the change at #756.

**Comment by BaronKrause** [comment]
Happens on my Samsung S8+ since today's update.

Also I cant search passwords anymore since the on screen keyboard closes almost immediately every time. Worked prior to this update.

**Comment by isabelrios** [comment]
@eliserichards FYi this is also happening every time you delete a login entry. Please see video: https://youtu.be/XoXP55Vyzf4

**Comment by linacambridge** [comment]
This stands out in the log:

> 2019-06-26 15:55:39.498 25887-25914/? I/sync15::sync_multiple: Syncing passwords engine!
> 2019-06-26 15:55:39.499 25887-25914/? I/sync15::sync: Syncing collection passwords
> 2019-06-26 15:55:39.500 25887-25914/? W/sync15::sync: can't setup for the passwords collection - hopefully it works later
> 2019-06-26 15:55:39.504 25887-25914/? I/sync15::sync_multiple: Sync of passwords was successful!

That should only happen if the state machine cycles too many times (which would warn ⚠️), or if the collection is declined (explicitly unchecked in `about:preferences#sync`) or not in `meta/global` at all. Do you remember if you first signed in to the account on Lockwise, or in another app, @LaurentiuApahideanSV?

It sounds like we could add better logging for this to a-s, too. 😕

**Comment by isabelrios** [comment]
Adding label to try to respond to Lina's question and provide more info if possible about this issue. 
Thanks!

**Comment by LaurentiuApahideanSV** [comment]
I have checked the browsing history of the account and it was created from Firefox not from Lockwise. I have also retested the issue on Lockwise 1.1.3 (4590) and it does not occur anymore, logins are successfully retrieved.
