### ISSUE TITLE
On screen Keyboard minimizes immediately on fxa login, search, and feedback forms

### ISSUE THREAD

**Issue by BaronKrause** [mozilla-lockwise/lockwise-android#798]
Since today's update, the onscreen keyboard when clicking search closes immediately. Ive tried different keyboards, all the same.

It worked before the update, and works fine in other apps.

This is on a Samsung S8+

**Comment by linuxwolf** [comment]
From my own testing on a Pixel 2 with version 1.1.2 (4405):

* tap Search
* briefly shows keyboard and "Search logins" in the titlebar, then reverts back to list entries
* tapping system Back brings the keyboard back and "Search logins" in the titlebar

**Comment by snapdeus** [comment]
This was happening to me.  I cleared the cache and it seemed to return to normal.

**Comment by eliserichards** [comment]
This is a known issue with Android keyboards, and can be mitigated by clearing the cache on your phone, but it is definitely still a headache for users. Other workarounds: pressing the back button or clicking in the search field brings the keyboard back up. 

I think there is some work that can be done around making sure that the focus is always set for the keyboards in the `FilterFragment`. We are using `requestFocus()` now:

```
    override fun onResume() {
        super.onResume()
        view!!.filterField.requestFocus()

        val inputMethodManager = context?.getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager
        inputMethodManager.showSoftInput(view!!.filterField, InputMethodManager.SHOW_IMPLICIT)
    }

    override fun onPause() {
        val imm = context?.getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager
        if (imm.isAcceptingText) {
            imm.hideSoftInputFromWindow(view!!.filterField.windowToken, 0)
        }

        super.onPause()
    }
```

**Comment by klint** [comment]
Hi. Clearing the cache does not solve anything in my case.
Also, this is the only app where this happens, on my phone. And I have plenty ;)

**Comment by eliserichards** [comment]
https://github.com/mozilla-mobile/android-components/blob/master/components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/View.kt

**Comment by pwd-github** [comment]
This should be P1. It's highly frustrating.

**Comment by klint** [comment]
And makes the search almost unusable!

**Comment by MadeOfMagicAndWires** [comment]
This seems to affect password auto-fill for me as well.

Possible work around is to just go to different fragments like the FAQ and single login details screens a couple of times (which will also just immediately close and reset to the main list view) multiple times until it sticks and you can use the search input again.   
For auto-fill simplest way is to just kill the app, refresh the login page, and wait for the background service to start up again.

**Comment by eliserichards** [comment]
See also : https://github.com/mozilla-lockwise/lockwise-android/issues/780
