### ISSUE TITLE
Using Lockwise with inflated accessibility options is horrid

### ISSUE THREAD

**Issue by pwd-github** [mozilla-lockwise/lockwise-android#799]
## Steps to reproduce
1. Increase font size and display size
2. Attempt to sign in to app 

### Expected behavior
Should work smoothly

### Actual behavior
whatarethose.gif

Though in seriousness, it's just horrid. 

### Device & build information
* Device: Pixel 2 XL
* Build version: 1.1.12
### Notes
Attachments:

**Comment by eliserichards** [comment]
Closing this in favor of a more general accessibility analysis issue :)
