### ISSUE TITLE
Login entry is not shown fine when its website is very long

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockwise/lockwise-android#805]
## Steps to reproduce
Save a credential from a website with long name
### Expected behavior
All fields are shown correctly
### Actual behavior
The credential is not shown fine on login list. Please see screenshot:
<img width="315" alt="Screenshot 2019-07-03 at 11 07 50" src="https://user-images.githubusercontent.com/1897507/60579909-593e2680-9d84-11e9-8783-1456f12163e1.png">

### Device & build information
* Device: Pixel 3
* Build version: master 17605c3480b58fac9075e6a6b08065f06a4c984c

**Comment by isabelrios** [comment]
Also in Login details view, the website is overlapped by the go to website icon:
<img width="300" alt="Screenshot 2019-07-03 at 11 20 00" src="https://user-images.githubusercontent.com/1897507/60580003-95718700-9d84-11e9-9546-29ce7c522247.png">

**Comment by abodea** [comment]
Verified as fixed in the latest build **`1.1.3 (Build 4584)`** using Samsung Galaxy s10+(Android 9).
