### ISSUE TITLE
Record sync request telemetry events

### ISSUE THREAD

**Issue by yuvalwolf** [mozilla-lockwise/lockwise-android#814]
Related #810 

### Vision statement / What / Requirements
Add telemetry events that allow us to:
- Track the number of successful sync requests
- Track the number of unsuccessful sync requests in which we receive an exception or the sync triggers a timeout.
    - Record the exception, if one is returned.

### Impact
Determine the percentage of sync requests that are successful, allowing us to better assess the frequency and coverage of sync-related issues.

**Comment by eliserichards** [comment]
Wanted: itemId, error message.

Question for Elise: how hard would this be to add to every telemetry event?

Todo: update metrics.md to reflect these changes (maybe @yuvalwolf can do this? 😉)
