### ISSUE TITLE
New credential not syncing from Firefox for Android

### ISSUE THREAD

**Issue by snapdeus** [mozilla-lockwise/lockwise-android#817]
1. Create a new account
2. Select "Remember" when Firefox for Android asks if it should remember the username & pw
3. The username and password do not ever appear in the lockwise app.
_____________

I expected the username and password to appear in lockwise.

### Actual behavior

The username and password does not appear in Lockwise.  I've waited over a day, continually re-syncing my Firefox for Android app, and the Lockwise app.

I end up having to manually copy the password from my mobile device to the lockwise firefox extension on my desktop.

### Device & build information
* Device: Oneplus 6
* Build version: Lockwise 1.1.2 (4405)

**Comment by ListeningGarden** [comment]
I believe this is likely related to the sync issues being investigated in #810

**Comment by LaurentiuApahideanSV** [comment]
I have tried to reproduce this issue on the latest build 2.0.0 (4831) using a Samsung Galaxy S9 (Android 8.0.0) but was unable to. After creating a new account in Firefox and logging in with the same account in Lockwise the credentials were successfully retrieved. Based on my comment I will remove the QA Needed Tag.
