### ISSUE TITLE
Create entry view and routing

### ISSUE THREAD

**Issue by eliserichards** [mozilla-lockwise/lockwise-android#821]
## Requirements
* Tapping the plus button from the entry list (android) opens the new entry screen
* Once saved, the user is routed to the read-only detail view (no toast)
* Make sure the item list is synced so that the new entry will be seen there too
* Tapping the 'X' button will cancel the creation of a new credential #823 
* Field validation and errors served on required fields #822 

## Visual Design
Invision: https://mozilla.invisionapp.com/share/3SN35UHWJDX#/screens/344499818

Zeplin: https://app.zeplin.io/project/5b6895bfe4af825140aa8dbc/screen/5c548fc35f8c1d3577504065

**Comment by abodea** [comment]
Verified as fixed on **v.4.0.0(6016)** using **Google Pixel 3 XL(Android 9), Samsung Galaxy S10+(Android 9).**
