### ISSUE TITLE
Manual create field validation

### ISSUE THREAD

**Issue by eliserichards** [mozilla-lockwise/lockwise-android#822]
Depends on #821, #1084 
Related to #603 

## Requirements
* Field validation and errors served for incorrect hostname (missing 'http://' or 'https://')
* Field validation and errors served for empty hostname and/or password

## Visual Design
**Invision**
Hostname - incorrect: https://mozilla.invisionapp.com/share/3SN35UHWJDX#/screens/344499820
Hostname/password - empty: https://mozilla.invisionapp.com/share/3SN35UHWJDX#/screens/344510982

**Zeplin**
Hostname: https://app.zeplin.io/project/5b6895bfe4af825140aa8dbc/screen/5c548fc3707f5443601a2d9d
Password - empty: https://app.zeplin.io/project/5b6895bfe4af825140aa8dbc/screen/5c548fc34e168142a92beddd

**Comment by mnoorenberghe** [comment]
> Field validation and errors served for incorrect hostname (missing 'http://' or 'https://')

You should not limit the scheme to those protocols, only ensure that there is a protocol.

**Comment by eliserichards** [comment]
Fixed by #1093

**Comment by abodea** [comment]
Verified as fixed on **v.4.0.0(6016)** using **Google Pixel 3 XL(Android 9), Samsung Galaxy S10+(Android 9).**
