### ISSUE TITLE
Manual create discard changes

### ISSUE THREAD

**Issue by eliserichards** [mozilla-lockwise/lockwise-android#823]
Depends on #821 

## Requirements
* Should have to confirm when cancelling changes and leaving the create view
* Routes to item list view when cancelled (need to confirm this)
* No confirmation required if all fields are empty. Otherwise, show discard change dialogue if any data has been entered

## Visual Design
**Invision**
Confirm dialog - https://mozilla.invisionapp.com/share/3SN35UHWJDX#/screens/347989571
**Zeplin**
Confirm dialog - https://app.zeplin.io/project/5b6895bfe4af825140aa8dbc/screen/5c6dc0201deeae99bc1712ca

**Comment by eliserichards** [comment]
Fixed by #1093

**Comment by abodea** [comment]
Verified as fixed on **v.4.0.0(6016)** using **Google Pixel 3 XL(Android 9), Samsung Galaxy S10+(Android 9).**
