### ISSUE TITLE
Display toast when new entry is saved

### ISSUE THREAD

**Issue by eliserichards** [mozilla-lockwise/lockwise-android#824]
Depends on #821 

## Requirements
* Display toast on display item screen to confirm new entry creation
<img width="325" alt="image" src="https://user-images.githubusercontent.com/43795363/71738931-b8592280-2e1d-11ea-8abb-7031dc989e84.png">

## Visual Design
**Zeplin:** https://zpl.io/2GRdAR3

**Icon:** [success-icon.zip](https://github.com/mozilla-lockwise/lockwise-android/files/3779773/success-icon.zip)

**Comment by changecourse** [comment]
Removing this from MVP functionality for 1.4.0.

Updated the functional requirements in #821 to transition from the create view to the read-only view of the login detail, removing the need for a confirmation toast at this time.

We can revisit if we feel this is necessary in the future. (After performing a competitive analysis of the feature, no one displays toast confirmations, it is implied by the routing to the read-only state)

**Comment by eliserichards** [comment]
Is this still on the table for Skyline? @changecourse @sandysage

**Comment by jhugman** [comment]
This would be a good time to rationalize our toasts and progress bars into the `RoutePresenter`, in the same way as we have done with `DialogAction`s.

We should put all these into the activity XML rather than the separate fragment XML files.

**Comment by abodea** [comment]
Verified as fixed on **v.4.0.0(6016)** using **Google Pixel 3 XL(Android 9), Samsung Galaxy S10+(Android 9).**
