### ISSUE TITLE
Amazon missing autofill credentials in Fenix

### ISSUE THREAD

**Issue by krzyk** [mozilla-lockwise/lockwise-android#854]
## Steps to reproduce
1. Launch Fenix
2. Go to amazon.com
3. Click on Sign In icon at the top (where a person icon is).
4. Click on "Sign-In. Already a customer?"
5. Click on "Email" or "Amazon password" field
### Expected behavior
I see lockwise prompt to autofill the credentials.

### Actual behavior
Nothing happens, I need to enter the credentials manually.

### Device & build information
* Device: Pixel 3
* Build version: 1.1.2 (4405)
### Notes
Same thing happens when I go to https://www.wykop.pl/zaloguj/ form in Fenix, no autocompletion.

**Comment by eliserichards** [comment]
Known issue with autofill on some sites. Parent issue: #393
