### ISSUE TITLE
Tapping on the search button auto-refreshes the entries screen and the keyboard is dismissed

### ISSUE THREAD

**Issue by jmcs** [mozilla-lockwise/lockwise-android#855]
## Steps to reproduce
1. Open the application
2. Try Searching

### Expected behavior
1. Search terms appear in the search box
2. Matching credentials appear bellow

### Actual behavior
- Application goes back to `All Logins` screen after 1 or 2 seconds for the first few times I try (usually I need more than 10 tries).

### Device & build information
* Device: Huawei P30 (ELE-29) - EMUI Version 9.1.0
* Build version: 1.1.1 (4590)
### Notes
Attachments:

**Comment by AndiAJ** [comment]
Hi, reproducible on Lockwise 1.1.3(4590) using a Google Pixel 3XL (Android 9).

**Comment by yuvalwolf** [comment]
This issue seems to be duplicating #798. Please make sure that when creating bug reports, they do not duplicate already *open* bug reports.

**Comment by jmcs** [comment]
Closing as duplicate of #798. (I searched for the issue before creating a new one, but didn't find anything)
