### ISSUE TITLE
"Provide Feedback" - "Other - Write In" section text box isn't centered 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-lockwise/lockwise-android#857]
## Prerequisites
1. Log in with a valid account

## Steps to reproduce
1. Tap the upper left hamburger button (next to the All logins button)
2. Tap Provide Feedback
3. Tap on the "Other - Write In" tab from the 2nd or 3rd section
4. Observe the text box

### Device & build information
* Device: Google Pixel 3XL (Android 9)
* Build version: 1.1.3 (Build 4584)
### Notes
Attachments: 

![rsz_2ndhead](https://user-images.githubusercontent.com/51314259/62033435-987d5d00-b1f4-11e9-9c36-62fd07182071.jpg)
![rsz_2ndother](https://user-images.githubusercontent.com/51314259/62033439-9c10e400-b1f4-11e9-89d4-bd0561a2d043.jpg)
![rsz_3rdhead](https://user-images.githubusercontent.com/51314259/62033441-9ddaa780-b1f4-11e9-8932-bb9a80e1d927.jpg)
![rsz_3rdother](https://user-images.githubusercontent.com/51314259/62033448-a16e2e80-b1f4-11e9-95f3-1998e94af8a9.jpg)

**Comment by yuvalwolf** [comment]
Updated the CSS of the survey. This should be fixed now.
