### ISSUE TITLE
Add "No internet connection" notification bar to be displayed in all lockwise menus

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#860]
### Why/User Benefit/User Problem
As a Lockwise user, I want when the internet connection is off, no matter in what menu I'm to be able to see that.
### Acceptance Criteria (how do I know when I’m done?)
The "No Internet Connection" notification bar is displayed in every lockwise menu while being offline.

**Comment by eliserichards** [comment]
Parent issue for network connectivity improvements: #373
