### ISSUE TITLE
Refine sync telemetry probes

### ISSUE THREAD

**Issue by eliserichards** [mozilla-lockwise/lockwise-android#862]
### Acceptance Criteria
- Look at current sync telemetry and identify any areas that need additional engineering from @eliserichards 
- Do we have the correct data to identify possible areas of improvement in sync?
- Possibly add an id for each sync request (see Leif's comment below)

Telemetry: https://sql.telemetry.mozilla.org/queries/63939/source#163430

**Comment by ddurst** [comment]
@irrationalagent From our conversation earlier, this is where we'd want to define how to better track sync request's "telemetry lifecycle" (pardon the expression) and what changes you'd need Engineering to supply.

**Comment by irrationalagent** [comment]
So a quick first look, there are many more sync end events than sync start events

https://sql.telemetry.mozilla.org/queries/63939/source#163430

Is it wrong to say that each start event should have at most one end event? Or is it the case that we can have one sync start event, and if there are multiple end events e.g. in the case that there were multiple retries that failed ("ended")?

It also seems that most of the "missing" sync_start events are around the beginning of the session, is it the case we are missing events there e.g. during first sync on app startup?

https://sql.telemetry.mozilla.org/queries/63936/source#163420

@eliserichards dave and I were thinking of ginning up a "sync id" - a random value that would be generated on each sync start and then be associated with all sync events (timeout, error, end) that occur as part of the same sync. This would allow for easier analysis on a per-sync basis. How hard would this be?
