### ISSUE TITLE
Update FAQ links & feedback to point to support.mozilla.com articles

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockwise/lockwise-android#873]
### Why/User Benefit/User Problem
Right now we're not able to adequately support our users well with Discourse and our obligatory email address in the app store. The Firefox Support team is stepping in to better cover our product support needs, which requires some updates on our side.

Mapping here: https://docs.google.com/spreadsheets/d/16bKy18uXTGHMAG7UVZbVRoxd_RNgKGaKtmbnR_D9LFQ/edit#gid=0

**Comment by changecourse** [comment]
@eliserichards I went through the mapping spreadsheet and added two columns, one for identifying which section of our app the current link is in, and one column to decide whether we should 'keep, remove, or add' a link based on the latest SUMO articles. 

Furthermore, I greyed out the fields that are not pertinent to our effort, so any changes will only have to be made on white background rows. 

Please reach out with any questions or concerns upon digging into the material above.

**Comment by abodea** [comment]
Verified as fixed on **v.4.0.0(6016)** using **Google Pixel 3 XL(Android 9), Samsung Galaxy S10+(Android 9).**
