### ISSUE TITLE
Clicking on text input routes back to Item List

### ISSUE THREAD

**Issue by eliserichards** [mozilla-lockwise/lockwise-android#888]
I believe this is happening with the searchbar as well as Edit.

## Steps to reproduce
1. Login to the app
2. Select an entry from the item list
3. From item detail, click on the kebab menu and select `Edit`
4. In the edit view, click on the hostname (as if you wanted to edit that text)
5. See that you are routed to the item list
6. If you click on the item again, it keeps popping back to the item list

### Expected behavior
A user is able to edit text without having to try 2+ times.

### Actual behavior
A user has to go through the motions of being routed back to the item list, select the item again, and when the re-routing to the item list stops, finally edit your entry.

### Device & build information
* Device: Pixel 3

**Comment by flomertens** [comment]
I see the same problem on a OnePlus 3T running lineage OS
