### ISSUE TITLE
[UITests] Clicking on Use test data button closes the app

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockwise/lockwise-android#898]
The first test in AppRoutePresenterTests fails after changes added in recent commit: fecc2f09104f1b161c0953acd160cccaec988c76

Looks like when clicking on Use test data button now the app is closed and so the test fails. See BB test results [here](https://addons-testing.bitrise.io/builds/7c4a8b1c93600529/testreport/ftl/testsuite/0/testcases?status=failed)
Launching the app again starts on the `ItemListView`

**Comment by isabelrios** [comment]
@jhugman is this change something intentional or should the app behave as before when clicking on that `USE TEST DATA` button? 
Thanks!

**Comment by eliserichards** [comment]
This is not intentional behavior. Adding the defect tag 😱
