### ISSUE TITLE
Edit View: There is no disclaimer menu when tapping on Delete Entry from Edit View

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockwise/lockwise-android#904]
## Steps to reproduce
Open one entry
Tap on hamburger menu -> Edit
Tap on Delete Entry
### Expected behavior
I would expect a disclaimer in case I regret removing the entry
### Actual behavior
There is no disclaimer to confirm the deletion, upon clicking on Delete entry, that's removed
### Device & build information
* Device: Pixel 3, API 28
* Build version: latest master b07e161

**Comment by eliserichards** [comment]
@changecourse should the delete confirmation dialog be shown in this case? I can't tell from invision/zeplin

**Comment by changecourse** [comment]
Yep! 

https://zpl.io/aX3m958

**Comment by isabelrios** [comment]
This Disclaimer has been checked by QA as a first step when PR landed on master. It was looking good. Removing the label at the moment. More testing will be done when the full Edit feature is tested via PI request.
Moving the card to Done
