### ISSUE TITLE
Crash - App crashes accessing several times to Edit/Delete entry

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockwise/lockwise-android#905]
## Steps to reproduce
I don't have exact steps yet, but I have seen the crash many times when going to Edit entry, Discard or Cancel, then go to Delete entry and cancel. Repeating these steps the app crashes.
### Expected behavior
App should not crash
### Actual behavior
The app crashes following several steps. It is not a common case to follow those steps but the crash may appear in a regular use so it may be better to investigate
### Device & build information
* Device: Pixel 3, API 28
* Build version: Latest master
### Notes
I got some logs, hope this helps.
Attachments: 

[editView crash.docx](https://github.com/mozilla-lockwise/lockwise-android/files/3579372/editView.crash.docx)

**Comment by eliserichards** [comment]
Crashes are a result of our routing changes - this is a developer bug and a route is missing somewhere. Might be fixed in #890

**Comment by isabelrios** [comment]
Following the steps to reproduce the issue seems to be fixed in master 9799eb8abf96b38c1716f46c9cae9fdfe30f2cd5
