### ISSUE TITLE
App crashes when tapping on an entry when Search view is open

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockwise/lockwise-android#906]
## Steps to reproduce
Once the ListView is loaded tap on the Search icon
Without entering any text, tap on one entry
### Expected behavior
The entry detailed view is open
### Actual behavior
The app crashes
### Device & build information
* Device: Pixel 3, API 28
* Build version: latest master b07e161
### Notes
I think this is a **regression**, tested a previous commit 7b77b4eee23fef7281d3ea408ade830681ff45f0 and it was working fine. I will try to get the commit causing the issue.

This is the log file I got when reproducing the issue:
[crash.txt](https://github.com/mozilla-lockwise/lockwise-android/files/3579532/crash.txt)

**Comment by eliserichards** [comment]
Related to #890 / #798.

**Comment by isabelrios** [comment]
This is not reproduced on master 9799eb8abf96b38c1716f46c9cae9fdfe30f2cd5
