### ISSUE TITLE
Fixup ignored autofill UI tests as unit tests

### ISSUE THREAD

**Issue by jhugman** [mozilla-lockwise/lockwise-android#910]
### Vision statement / What / Requirements
There are several autofill UI tests that are not being run, and quite a lot of autofill code not tested at all.

This issue asks for the tests to re-enabled as unit tests.

### Acceptance criteria

When `ParseStructureBuilderTest` is passing on CI, loading XML from disk.

**Comment by isabelrios** [comment]
@jhugman @eliserichards I have checked that the tests in [Autofill Test suite ](https://github.com/mozilla-lockwise/lockwise-android/blob/master/app/src/androidTest/java/mozilla/lockbox/uiTests/AutofillTests.kt)run successfully if we enable them again as part as the regular UI run, let me know if you want me to uncomment them so at least the existing ones (`testBasicFixtures` and `testRealFixtures`) start running
