### ISSUE TITLE
Clicking on the search button doesn't open search prompt

### ISSUE THREAD

**Issue by agi90** [mozilla-lockwise/lockwise-android#914]
## Steps to reproduce
- Click on search button

### Expected behavior
- Search prompt opens

### Actual behavior
- Search prompt opens and closes really fast

### Device & build information
* Device: Samsung S10
* Build version: Latest from Play store

**Comment by eliserichards** [comment]
This has just been fixed in #890! It will be fixed in the next release! 😄

**Comment by agi90** [comment]
Nice to hear! Thanks 🎉
