### ISSUE TITLE
The entries are not displayed for the first time when logging in

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#924]
## Steps to reproduce
1. Install and launch Lockwise.
2. Login with valid credentials.
3. On the entries screen wait until the accounts are displayed.
### Expected behavior
All the entries are displayed.
### Actual behavior
Nothing is displayed until a refresh.
### Device & build information
* Device: **`Samsung Galaxy S10+(Android 9) and Samsung Galaxy s9(Android 8), Google Pixel 3A(Android 9) `**
* Build version: **`v2.0.0 (Build 4824)`**
### Notes
Please note that this issue occurs only for the first time when logging in. After a refresh the entries are displayed or after re-launching the app the entries are displayed.
[log.txt](https://github.com/mozilla-lockwise/lockwise-android/files/3615124/log.txt)
Note that on Samsung Galaxy S8+(Android 8) and OnePlus(Android 9) I couldn't reproduce the issue.

**Comment by isabelrios** [comment]
Adding qa-needed label so that we reproduce in previous build to get more insights about a possible regression or a new issue.

**Comment by isabelrios** [comment]
I can't reproduce this issue with builds:
1.1.4 (Build 4673) 
2.0.0 (Build 4831) 

Using Pixel 3, Android 9 device. Installing the app with `adb install ...apk`and launching the app for the first time with my account. 
I have tried also with and without securing the device. But I may be missing some other configuration used while reproducing the issue. I will leave the `QA Needed`label so that @abodea comments on this too to have at least another person looking at this.

**Comment by ddurst** [comment]
@abodea Are you able to consistently reproduce this? I'm curious about Pixel 3A vs Pixel 3 (your test vs Isabel's).

**Comment by abodea** [comment]
@ddurst I re-tested on two devices: **`Google Pixel 3XL(Android 9) and Google Pixel 3a XL(Android 9)`** using the **`2.0.0(4831)`**.
Note that I couldn't reproduce the issue anymore, once I reached the entries screen, it started to sync.
I believe we can close this issue and I will try to keep an eye on this issue while testing and re-open/add a new issue if it will happen again.

**Comment by abodea** [comment]
@ddurst I close this issue as I re-checked it on few devices: Google Pixel 3 Xl(A9), Google Pixel 3a XL(A9), Samsung Galaxy S10+(A9), Samsung Galaxy Note 9(Android 8.1) but everything worked as expected. In case I will reproduce this issue I will re-open it or, re-open another one. 
Tested on the latest build from Master.
