### ISSUE TITLE
Sign in button is hidden behind the keyboard. There is no automatic scroll to show it.

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockwise/lockwise-android#929]
## Steps to reproduce
Enter email and tap on `Continue` button so that the password screen is shown
### Expected behavior
Once the password field is focused the view should scroll up so that the field is seen completely as well as the `Sign in` button
### Actual behavior
The view does not scroll up so the `Sign in` button is hidden. If you press enter in your device it will be clicked but I would expect to see it without having to scroll manually. Please see screenshot attached.
### Device & build information
* Device: Pixel 3, Android 9
* Build version: v2.0.0 (Build 4824)

![IMG_3821](https://user-images.githubusercontent.com/1897507/65050918-76889700-d968-11e9-9552-a15bbd449758.JPG)

**Comment by Diana-Rus** [comment]
Hi, I encounter the same issue with Google Pixel 3a XL (Android 9), Samsung Galaxy S8+ (Android 8.0.0) and Sony Xperia Z5 (Android 7.0), but in my case, not only the "Sign In" button is affected but also the password field.

Note: 
- This only happens on the "Sign in" page.
- The issue does not have the same impact on Google Pixel 3a XL (Android 9), Samsung Galaxy S8+ (Android 8.0.0) as the softkeyboard is placed right after the "Sign in" button.

**Comment by isabelrios** [comment]
@eliserichards This looks much better now 🎉  Although the scroll is not automatic, you can scroll the screen and so see and tap on the sign in button successfully. I would say this is closed unless we want that scroll to be automatic? In that case we could open a follow up issue less critical... what do you think @changecourse? 

Thanks!

**Comment by abodea** [comment]
Verified as fixed on **`v3.0.1 (Build 5124)`** using Google Pixel 3a XL(Android 9). Based on the @isabelrios comment.

**Comment by changecourse** [comment]
@isabelrios interesting... on my Pixel 2, the scroll is automatic, which is certainly preferred. 

I agree, a follow-up issue would be good for this.
