### ISSUE TITLE
autofill: Collect new credentials from a login page/app that FxA has not seen before.

### ISSUE THREAD

**Issue by jhugman** [mozilla-lockwise/lockwise-android#933]
This is for accounts that the user already owns, but lockwise does not know about.

**Comment by eliserichards** [comment]
Is this the same workflow as a user creating a brand new account? From autofill's perspective I would assume (disclaimer: huge assumptions on my part) that the fields for standard "log in to existing account" and "create a new account" pages would be labeled the same way for username/pwd fields, and that the view node would parse them the same way?

**Comment by eliserichards** [comment]
This is fixed by #217
