### ISSUE TITLE
Login screen always reloads

### ISSUE THREAD

**Issue by leo-unglaub** [mozilla-lockwise/lockwise-android#937]
## Steps to reproduce
Open the app and try to enter an email address and a password.

### Expected behavior
The page should not reload before the email/password is entered fully.

### Actual behavior
The site reloads every 2 seconds, so its impossible to type in the password and you cannot login.

### Device & build information
* Device: Nokia 8.1
* Build version: Android 9, Latest updates from 1. September

**Comment by isabelrios** [comment]
Could it be due to the same reason as in #923? The behavior described looks very similar

**Comment by leo-unglaub** [comment]
It looks very similar, with one big difference. In #923 the behavour is described as restarting the app, but in my case its just reloading. But it might be related.

**Comment by isabelrios** [comment]
Let me share a video of #923 because is not that the app restarts, the full app, is only the login view that as you say it is like reloading the full time, when you have to enter the email.

**Comment by isabelrios** [comment]
@leo-unglaub please see: https://youtu.be/Z_fxrLxGJw0
@abodea could you confirm if that is what seen in #923? 
Thanks!

**Comment by leo-unglaub** [comment]
@isabelrios yes, it is very similar. Sometimes i get to the password field, but i never manage to type something before it reloads. So it is the same problem i asume. Thanks so much for posting the video. :)

**Comment by abodea** [comment]
Hello @isabelrios, I just re-tested this issue on **`Samsung Galaxy S10+(Android9) and Huawei Mate20 Pro(Android 8.1)`** but I couldn't reproduce the issue.
I believe it is the same issue as #923.
Please note that on one device, I updated it from store. I was able to login without problems.
Can you please go to **`Device Settings > Search for Autofill > Set it to None > Restart Lockwise > Login.`**

**Comment by isabelrios** [comment]
I guess the condition to see this issue is as reported in #923 having the Autofill set to Lockise before signing in. Did you have that already set @leo-unglaub? 

If so, @abodea we can close this issue as dup of the other, highlighting that pre-condition as needed to see the issue, otherwise is not reproducible.

**Comment by leo-unglaub** [comment]
@isabelrios i veryfied the issue. It is a dublicate of the linked issue. As soon as i unset the autofill it works fine. So i assume the app should never try to autofill itself.

Thanks for looking into it!
Greetings
Leo

**Comment by abodea** [comment]
Thank you for the responses @leo-unglaub!
Yes indeed the app shouldn't never try to autofill itself. We will keep tracking that issue and see what will be the solution.
Dupe of #923.

Thanks,
Andrei
