### ISSUE TITLE
Prevent entry duplication during edit

### ISSUE THREAD

**Issue by eliserichards** [mozilla-lockwise/lockwise-android#948]
## Story Description

We should not be saving a duplicate of an existing login when editing an entry. It is possible to edit an entry by changing the username to conflict with one already saved for that `origin`/`formActionOrigin`/`httpRealm` combo.

### On "Edit Login" Screen

**InVision:** https://mozilla.invisionapp.com/share/QRU9LDSZ8EH
**Zeplin:** https://app.zeplin.io/project/5b6895bfe4af825140aa8dbc/screen/5d9b96331d02d5069eb3e1ba

### On "Create Login" Screen

**InVision:** https://mozilla.invisionapp.com/share/P4U9LDZ8K6N
**Zeplin:** https://app.zeplin.io/project/5b6895bfe4af825140aa8dbc/screen/5d9b962f845d361e5ec678c5

### host name

**has to have http:// or https://**
- We don't have such a restriction in any of the Firefox browsers so I don't see why we should have that in Lockwise. The origin field is a URI, not a URL e.g. ftp://example.com, file:///, and chrome://FirefoxAccounts are all values that we currently store and Sync.
- You should also ensure that there are no path segments i.e. https://www.example.com is valid whereas https://www.example.com/ and https://www.example.com/foo are invalid.
- We decided not to allow editing of this field on desktop for now because users can make changes to it which break autofill so you could also de-prioritize editing of the origin and only allow editing this field for new logins

### username
- should check (after text changes? on save?) that the username does not exist for that hostname already

**Comment by eliserichards** [comment]
Open questions: 
- when do we want to check if the duplicate exists? While they are editing? On save?
- how do we want to inform the user that their edits are invalid? popup message? error text? (_needs copy_)
- do we want to mimic desktop and disable editing the `hostname` field?

**Comment by changecourse** [comment]
Within the context section of the description above, @mnoorenberghe states that "We don't have such a restriction in any of the Firefox browsers so I don't see why we should have that in Lockwise. The origin field is a URI, not a URL e.g. ftp://example.com, file:///, and chrome://FirefoxAccounts are all values that we currently store and Sync." This should be considered a parity effort for both iOS and Android, and created as a separate issue. (@sandysage @ddurst let me know if you agree)


Now as for this issue, to prevent entry duplication during edit: 

>when do we want to check if the duplicate exists? While they are editing? On save?
On save

>how do we want to inform the user that their edits are invalid? popup message? error text? 
The error will need to be associated with the field that has been changed, which causes the duplication error, so one of the following three scenarios can occur:
1. the web address is changed, matching a login that already uses the same web address/username combination
2. the username is changed, matching a login that already uses the same web address/username combination
3. both the web address and username are changed, matching a login that already uses the same web address/username combination

In all instances, we'll use text validation error copy on the corresponding fields. Designs forthcoming. 

>do we want to mimic desktop and disable editing the hostname field?
@mnoorenberghe @sandysage I'd like to have a conversation about this... we should certainly be consistent everywhere, but my hope would be that we would allow editing of the host name (and if there's worry about someone breaking autofill experiences, we simply provide disclaimer text but still align with user expectations about being able to edit login entries)

**Comment by changecourse** [comment]
Copy for how we handle this on desktop, for context: "A login for [website address] with that username already exists."

**Comment by changecourse** [comment]
Per our conversation in sprint planning, we will be disabling the ability to edit the origin field, so we only need to worry about error validation for the following instances:

1. Someone edits a login, where they edit a username, and it matches a login with the same origin and username already saved 

2. Someone creates a login, where they choose the exact same origin and username as an already existing login

In both of these instances, I'd like to address with inline error validation following any attempts to create or save a duplicate, as we handle with other errors for CRUD. 

@mnoorenberghe does this all make sense to you?

**Comment by changecourse** [comment]
Added designs to the description. If @mnoorenberghe and @sandysage can provide a thumbs up to the above approach, that'd be great.

**Comment by mnoorenberghe** [comment]
@changecourse It's not as simple as what you're saying because it's okay to have two passwords for the same username and origin if the `httpRealm` or `formActionOrigin` is different. 
* `formActionOrigin` is something the user never sees so it's kinda unusual to include that in the checks we could stop including that in the unique key but we'd have to change Toolkit too. 
* `httpRealm` allows a user to have an HTTP auth. login and a form login with the same username for the same site. In fact, you can have different passwords for the same username on multiple different HTTP realms. An HTTP realm represents a different section (usually a directory) of a site.

Otherwise, what you're suggesting is fine.
