### ISSUE TITLE
Invalid token is shown after tapping on Continue once the the sigin in email has been confirmed

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockwise/lockwise-android#953]
### Notes
So far this has been seen with a debug build not a release. Adding QA Needed label, we'd need to test on Release build to check if it happens there but until then better to have an issue open and track this possible error...

## Steps to reproduce
Sign in to Lockwise after a few days not using it so that the confirm account email is received

### Expected behavior
After tapping on Continue once the sign in is confirmed with that FxAccount, Lockwise is open normally

### Actual behavior
Right after tapping on Continue you can see `Invalid token` for a few seconds.

### Device & build information
* Device: Pixel 3
* Build version: master, _debug build_

**Comment by abodea** [comment]
#### I tried to reproduce this issue following more scenarios but the login worked as expected and no `invalid token` was displayed:

```
First scenario

- Fresh install on Lockwise, 
- Create new account using a fresh email
- Close Lockwise
- After 1-2h re-open it and re-send the email confirmation.
- Confirm the login
- Successfully login

Second scenario

- Fresh install on Lockwise, 
- Create new account using a fresh email
- Send the email verification 5 times 
- Confirm the login from the email
- Successfully login

Third scenario

- Fresh install on Lockwise
- Create new account using a fresh email
- Send the email confirmation
- Close the app
- Wait 1h
- Confirm the login
- Re-launch lockwise
- Successfully login

**Comment by abodea** [comment]
I will also try today to sign-up with a new email and don't confirm the email until tomorrow I will post more updates once I will finish this test case.

**Comment by abodea** [comment]
Yesterday I left a device over night without confirming the email, I confirmed it today and I successfully login and the `invalid token` wasn't displayed.
Also, note that I found this issue https://github.com/mozilla/fxa/issues/564 regarding the invalid token issue wich I consider a general one and it's not really related to lockwise.

**Comment by jhugman** [comment]
@abodea @isabelrios 

> Actual behavior
> Right after tapping on Continue you can see Invalid token for a few seconds.

What happens after a few seconds?

I'm inclined to say if the app recovers, then we should close this out, and follow https://github.com/mozilla/fxa/issues/564 .

**Comment by isabelrios** [comment]
@jhugman After a few seconds, very quickly the app recovers and works as expected. So I agree on closing this one

**Comment by isabelrios** [comment]
As suggested above, let's close this issue and follow the fxa issue related.

**Comment by abodea** [comment]
Removing the QA Needed until further notice.
