### ISSUE TITLE
Backgrounding app during edit discards changes with no prompt

### ISSUE THREAD

**Issue by eliserichards** [mozilla-lockwise/lockwise-android#978]
### Current behavior
- open a credential
- edit credential, make some change to username/pwd
- background the app
- wait the autolock time (default is 5 mins)
- foreground the app. See that your changes are gone and you are on the item list

### Expected behavior
???????

## UI and Visuals

**Comment by eliserichards** [comment]
@sandysage @changecourse I realized that this is a case that we haven't spoken about yet. I outlined the current behavior above.

**Comment by changecourse** [comment]
The current behavior does preserve the data (rather than overriding) based on the unknown intent of the user (since they do not decide what to do, and let the lock timer secure their session)

IMHO, this functions as expected.

**Comment by sandysage** [comment]
Closing this issue since the behavior is as expected.
