### ISSUE TITLE
The underlines from Name and Web address are highlighted when tapping on the screen in Edit Login page

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#984]
## Steps to reproduce
1. Launch Lockwise.
2. Login with valid credentials.
3. Access any account.
4. Tap on 3 dot menu and enter the Edit Login mode.
5. Tap anywhere on the second part of the screen(where are no elements displayed).

### Expected behavior
Nothing happens.
### Actual behavior
The underlines from Name and Web address are highlighted.
### Device & build information
* Device: Google Pixel 3a XL(Android 9)
* Build version: Latest build from master(17/10/2019)
### Notes
Attachments: 
[Video](https://drive.google.com/file/d/1NqCCR6Sd3KE2gYKRiR4feJ8VKK0VuIiC/view?usp=sharing)

**Comment by sandysage** [comment]
I think this was also called in the UX review in #899. @eliserichards Was this addressed somewhere before we merged those updates and available elsewhere for testing? If not, do we need follow up issues for the remaining findings?

**Comment by eliserichards** [comment]
This wasn't addressed in #899. We just merged the things that were easily fixable and we're saving things (like this) for followups. This can be kept open to address the issue.

**Comment by sandysage** [comment]
Sa-weet! Thanks @eliserichards for helping me stay up to speed. Sorry to conflate 'all the things'.

**Comment by abodea** [comment]
Verified as fixed on **3.1.0 (Build 5362) with Google Pixel 3a XL(Android 10).**
