### ISSUE TITLE
After a home button interrupt(while being in Edit Login page) when returning the user is redirected to the entries screen 

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#985]
## Steps to reproduce
1. Launch Lockwise.
2. Reach the Edit Login page.
3. Tap on the home button in order to put Lockwise in background.
4. Resume Lockwise.
### Expected behavior
The Edit Login page is still displayed after a home button interrupt.
### Actual behavior
The Login page is dismissed and the user is redirected to the main page(entries section).
### Device & build information
* Device: Google Pixel 3a XL(Android 9)
* Build version: Latest build from master(17/10/2019)
### Notes
Attachments: 
[Video](https://drive.google.com/open?id=1NqCCR6Sd3KE2gYKRiR4feJ8VKK0VuIiC)

**Comment by abodea** [comment]
Re-checked on the latest build **`v3.0.0 - RC 1 with Google Pixel 3a XL(A9)`** and I can still reproduce this issue.
I will remove the `QA Needed` until further notice.

**Comment by eliserichards** [comment]
Needs to be reproduced on v3.3.0

**Comment by abodea** [comment]
I re-checked this issue on the latest build **4.0.0 (Build 6087)** with Samsung Galaxy S10+ (Android 9) and I couldn't reproduce it anymore.
Note that after resuming Lockwise, the right screen was displayed.
Based on my comment I will close this issue and if I will be able to reproduce it on the future versions, I will open a new bug.
