### ISSUE TITLE
The delete prompt is not dismissed after a home button interrupt

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#987]
Duplicate of #915 
Duplicate of #892 
Duplicate of #1016

## Steps to reproduce
1. Launch Lockwise.
2. Reach the Item Detail page.
3. Tap on the 3 dot menu and select delete.
4. Tap on the device home button in order to add Lockwise in background.
5. Resume Lockwise.
### Expected behavior
The account section is displayed with the Deleting prompt.
### Actual behavior
The entries section is displayed and the delete prompt is displayed over it.
### Device & build information
* Device: Google Pixel 3a XL(Android 9)
* Build version: Latest build from master(17/10/2019)
### Notes
Attachments: 
[Video](https://drive.google.com/file/d/1MR4AyeifFB5vLAH7g42xEzUMa_doilvs/view?usp=sharing)

**Comment by sandysage** [comment]
@abodea Does the overlay still work when you return back to the app? Or does it lock up the app entirely? I think we can live with that being the persistent state as long as the app still functions after you tap cancel or delete.

**Comment by abodea** [comment]
Re-checked on the latest build **`v3.0.0 - RC 1 with Google Pixel 3a XL(A9)`** and I can still reproduce this issue.

**Comment by abodea** [comment]
Verified as fixed on the latest build **3.3.0(5660) with Google Pixel 3a XL(Android 10).**
For more details please check the following:

| Case | Works? | 
|------------- | :-------------: |
| **Delete dialog is displayed after a home button interrupt(add the app to background)** | ❌ | 
| **Delete dialog works correctly after a home button interrupt**  | ✅   | 
| **Delete dialog works correctly after multitasking to another app**  | ✅| 
| **Delete dialog works correctly if no interrupt is performed**  | ✅   | 
| **Delete dialog works correctly when tapping on the cancel button** | ✅  | 
| **Auto Lock dialog is displayed after a home button interrupt(add the app to background)** | ❌ | 
| **Auto Lock dialog works correctly after a home button interrupt**  | ✅   | 
| **Auto Lock dialog works correctly after multitasking to another app**  | ✅| 
| **Auto Lock dialog works correctly if no interrupt is performed**  | ✅   | 
| **Auto Lock dialog works correctly when tapping on the cancel button** | ✅  | 

### Please note that for the cases marked with ❌ the behavior is the same in bot places Delete and Auto-Lock dialogs.
Note that if I add Lockwise to the recent application menu is different from adding Lockwise to the background.
- Adding Lockwise to the recent application menu and then resuming Lockwise, the `Delete dialog or Auto-Lock dialog is dismissed
- Adding Lockwise to the background and then resuming it(re-open from the home screen) the `Delete dialog or Auto-Lock dialog is dismissed

@jhugman @eliserichards  I would say that opening a new bug for this two cases where the `Delete and Auto-Lock dialogs` are dismissed is the best approach. Now there is no redirect to the item list and everything works well.
Can you please confirm if my verification is valid and if I should open a new bug for that case.

**Comment by abodea** [comment]
I synced with @eliserichards on slack and she agreed that it's fine to close this bug and open a new one only for the scenario when we add Lockwise to the background.
