### ISSUE TITLE
Duplicate checking should consider formSubmitURL and httpRealm

### ISSUE THREAD

**Issue by mnoorenberghe** [mozilla-lockwise/lockwise-android#989]
Follow-up to #948 which only checked `hostname` (aka. `origin`), not `formActionOrigin` (aka. `formSubmitURL`) or `httpRealm`. We want to align on a single definition of duplicate and this matches what we have done [in Toolkit](https://searchfox.org/mozilla-central/rev/17756e2a5c180d980a4b08d99f8cc0c97290ae8d/toolkit/components/passwordmgr/LoginManager.jsm#308-315) for a long time.

In the future [this should be handled in a-s](https://github.com/mozilla/application-services/issues/617) so apps just need to handle the errors. 

I would recommend renaming the function `getUsernamesForDomain` since `hostname` is a misnomer and other fields will also be checked.

## Steps to reproduce
1. Save an HTTP basic auth login at https://bugs.mattn.ca/pwmgr/login_and_change_form.html on desktop since I don't know if Lockwise on Android can save basic auth.
2. On https://bugs.mattn.ca/pwmgr/login_and_change_form.html save a login with a username other than 'user'.
3. On Lockwise for Android which is synced with the desktop account above, try to edit the username from step 2 to match the one from step 1 ('user').

Similar STR also exist for two form logins with different `formActionOrigin`s (you can change the `action` attribute to point to a different origin on any test page to test that).

### Expected behavior
The edit succeeds since they aren't duplicates: one is for HTTP auth and the other isn't

### Actual behavior
The edit is prevented because the logins share only the same origin and username.

**Comment by mnoorenberghe** [comment]
> As I understand it, this issue is to have the mobile app match what we do on desktop today. This still raises the more interesting problem around having these hidden fields in such a way that users don't have visibility in what constitutes a duplicate and what doesn't.

Only `formSubmitURL` (better known as `formActionOrigin` is hidden). `httpRealm` should be shown to users to differentiate from form logins and so the user knows with realm on the site the login is for. There can be multiple realms for the same site with the same username e.g. a different password for the invoice system vs. the payroll system on the same subdomain.

> For now, we can strive to have the same experience on mobile. But longer term we need to holistically consider how we think about duplicates across all the platforms.

Yeah, I agree. It would be more understable to not include `formActionOrigin` in the dupe checking but we also get complaints that users want logins to be even more granular than they are today and would like the path/directory also taken into account. I noticed the other day that Chrome does record paths for some of the login fields, not just origins.

Btw. there was a [discussion a few years ago about removing `formSubmitURL`](https://bugzilla.mozilla.org/show_bug.cgi?id=1121119) and I believe we have some telemetry on how often it doesn't match the form's origin.

As you said, in the short term I don't want to break editing of logins that aren't considered dupes on other platforms.

**Comment by ddurst** [comment]
@mnoorenberghe Oooo, we were talking about telemetry this morning as well. If you come across that, please link.

**Comment by mnoorenberghe** [comment]
It was linked in my last comment: https://bugzilla.mozilla.org/show_bug.cgi?id=1121119#c8 Comment 8 has analysis

**Comment by ddurst** [comment]
Yes, but a) those links are dead, b) that was from 5 years ago. I was hoping to look at more recent similar analysis (but it doesn't look like we have the same parameters to query on anyway).
