### ISSUE TITLE
Keyboard is not automatically hidden in entry list view when unlocking the app using a passcode

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockwise/lockwise-android#992]
## Steps to reproduce
Have a passcode set in the device.
Lock the app and unlock it
### Expected behavior
The entry list view is shown completely
### Actual behavior
The keyboard hides part of the entries. You have to manually hide it to see the full list

### Device & build information
* Device: Pixel Android 10
* Build version: master 2c445568b30be0432a85f27e6ae822248b6a9ff7

**Comment by isabelrios** [comment]
Right, that is described in issue #929

**Comment by changecourse** [comment]
@isabelrios @abodea I was unable to reproduce this issue on RC2, or rather the latest branch for #929 

Can you retest and see if this is still reproducible on the latest master?

**Comment by abodea** [comment]
@changecourse I was able to reproduce this issue using the latest **`RC 3.0.1 (Build 5124)`**.
For more details please see the [video](https://drive.google.com/file/d/1B37J0gI9YAb_J5NpFnhNpnxM8U79JSVX/view?usp=sharing)
In order to reproduce this issue, you need to have a passcode setup or any security method.

**Comment by changecourse** [comment]
Ah yes... I can also reproduce. 

When testing the fix for #929 yesterday, and using a pin, the keyboard was dismissing for me automatically, but only if I forced a lock via the menu.

**Comment by abodea** [comment]
Verified as fixed on the `3.1.0 (Build 5361)` with **Google Pixel 3a XL(Android 10).**
Note that everything worked as expected and the keyboard was not displayed anymore.
There was 1 minor bug that I found #1046.
